classes/OpenCFP/Application.php
The swiftmailer configuration in config/*.yml was not being passed to the swiftmailer provider correctly. This commit puts the swiftmailer configuration inside a swiftmailer.options array, which fixes the problem.
=> Fix swiftmailer configuration not being passed correctly

classes/OpenCFP/Domain/Entity/Mapper/Talk.php, classes/OpenCFP/Http/Controller/Admin/TalksController.php, templates/admin/talks/_table.twig, tests/unit/controllers/admin/TalkControllerTest.php
We have a lot of talks in our CFP (399 so far), and we need to be able to go through them in a more non-random order.
I'd like to set up filters, too, but that's a bit more ambitious.
=> Allow sorting on admin talks page

README.md
Just repointed my repositories and found some loose-ends from the move. 22a1c99 requires registration / update of the repository with Code Climate. TravisCI seems to have picked up everything alright.
=> Update badges of honor!

classes/OpenCFP/Application/NotAuthorizedException.php, classes/OpenCFP/Application/Speakers.php, classes/OpenCFP/Http/Controller/DashboardController.php, classes/OpenCFP/Http/Controller/TalkController.php, templates/dashboard.twig, tests/OpenCFP/Application/SpeakersTest.php
This was **technically** already possible if I'm understanding #153 correctly. What would happen is that you'd click "Edit" and be redirected with flash errors to the "View Talk" page. Kind of a round-about way of getting there.
That said, this was another opportunity to refactor logic out of controllers into the service layer so I did that. By doing so, we reduce criticality of coverage on at least that part of `TalkController` by having solid coverage on the service layer. The affected controller method is a refactor or two away from being a really basic "do this; redirect if it fails; otherwise, redirect to success"; which is good!
There's some copy+paste shenanigans to determine whether or not the CFP has ended. This is only important for required for rendering purposes. It would …
=> Adds capability for speaker to view talk after deadline.

classes/OpenCFP/Provider/DatabaseServiceProvider.php, tests/OpenCFP/Provider/DatabaseServiceProviderTest.php
This is quality-of-life work in response to the issues in #179. The service provider for our database connection through PDO now does a final check on the connection before registering PDO in the service container.
I implemented this as a "unit" test, but it's not really a unit test because PDO isn't mocked. I think that in this case (because we're getting some odd behaviour out of PDO regarding "invalid" DSNs) it is appropriate to not mock it.  If you would like me to move the test somewhere else or put it in an "integration" group, let me know and I'll adjust.
Current implementation fatally errors when invalid DSN provided (similar to what happens if you forget to `composer install` etc etc.):
```
Fatal error: Uncaught exception 'Exception' with message 'There was a problem connecting …
```
=> Adds pre-flight check to DatabaseServiceProvider

classes/OpenCFP/Http/Controller/PagesController.php, classes/OpenCFP/Provider/TwigServiceProvider.php, config/development.dist.yml, config/production.dist.yml, config/testing.yml, templates/_header.twig
When the CFP is on-going, everything is rendered as currently in `master`. When CFP has closed, an alternative message is shown on the homepage that includes how many talks were submitted. Took queue from [phptek](http://tek.phparch.com/call-for-papers-ended-with-620-submissions/) as far as whether or not number of submissions was "a standard thing to report".
Fixes part of #107.
This also implements a global Twig variable that indicates whether or not the CFP is open (`cfp_open`). This would be helpful for #183 to use rather than [sending it in the Twig context manually](https://github.com/mdwheele/opencfp/commit/2a2b3b0eb4a086defff0e265c502a1a115b99b94).
=> Adds visual indication of CFP ending on the homepage

tests/OpenCFP/Application/SpeakersTest.php
Missed writing a test for the new method on `Speakers` to get a specific talk. Added here.
=> Adds missing test for positive behaviour on Speakers#getTalk.

.gitignore, composer.lock
I think it would be better to have composer.lock in the repo - it has been put into the repo in the past (see #48 and #49) but looks like it was added to the .gitignore in commit 478c7ffe856fbe0e213de26f7aa34ec444151d86
=> Include composer.lock in the repo

tests/unit/controllers/DashboardControllerTest.php
Before: 
``` bash
PHPUnit 4.6.4 by Sebastian Bergmann and contributors.
Configuration read from /var/www/html/opencfp/phpunit.xml
................................................................. 65 / 76 ( 85%)
......R....
Time: 1.66 seconds, Memory: 82.75Mb
There was 1 risky test:
1) DashboardControllerTest::indexDisplaysUserAndTalks
Test code or tested code did not (only) close its own output buffers
OK, but incomplete, skipped, or risky tests!
Tests: 76, Assertions: 96, Risky: 1.
```
After: 
``` bash
PHPUnit 4.6.4 by Sebastian Bergmann and contributors.
Configuration read from /var/www/html/opencfp/phpunit.xml
................................................................. 65 / 76 ( 85%)
...........
Time: 1.74 seconds, Memory: 83.00Mb
OK (76 tests, 96 assertions)
```
=> End output buffer so that test is not flagged as risky

classes/OpenCFP/Domain/Services/ProfileImageProcessor.php, classes/OpenCFP/Domain/Services/RandomStringGenerator.php, classes/OpenCFP/Http/Controller/ProfileController.php, classes/OpenCFP/Http/Controller/SignupController.php, classes/OpenCFP/Infrastructure/Crypto/PseudoRandomStringGenerator.php, classes/OpenCFP/Provider/ApplicationServiceProvider.php, classes/OpenCFP/Provider/ImageProcessorProvider.php, composer.json, composer.lock, migrations/20150519122926_reset_photo_paths.php, tests/OpenCFP/Infrastructure/Crypto/PseudoRandomStringGeneratorTest.php
This pull request patches a flaw in how profile images are managed that creates risk of a persistent remote code execution vulnerability. Details of the vulnerability may be released at the maintainers' discretion.
- Uses `ircmaxell/random-lib` to generate reasonably random filenames whereby no part of the filename, at-rest, is controlled by a user of OpenCFP.
- Adds additional checks to cleanup profile photo uploads that have yet to be cropped and permanently stored.
- Adds a migration to clean existing installs of OpenCFP with regards to this vulnerability; bringing stored profile photos inline with proposed storage scheme.
**Potential Future Work**
- Would like to implement tests that attempt to exploit this vulnerability from an e2e perspective as well as tests that force exceptions …
=> Photo Upload Vulnerability

composer.json, composer.lock, phpunit.xml
This adds a listener for PHPUnit that detects tests that run over some threshold. I have set it to 300ms as that seemed to be a healthy start. There **are** some tests (3-4) that run around ~250ms so maybe bumping down is good? In addition, you can override this threshold for specific test methods. See more docs at https://github.com/johnkary/phpunit-speedtrap.
Build will not fail if it detects heavy tests, it's just to help improve when there is time. 
Example output:
``` php
PHPUnit 4.6.6 by Sebastian Bergmann and contributors.
Configuration read from /var/www/html/opencfp/phpunit.xml
...............................................................  63 / 108 ( 58%)
.............................................
You should really fix these slow tests (>300ms)...
1. 828ms to run …
```
=> Add PHPUnit Speedtrap to detect slow tests while in development.

config/development.dist.yml
While I agree that https is a sensible default for production, I think that normal http makes more sense in development environments. Feel free to reject this PR if you disagree.
=> Turn off https default for development environment

README.md, web/index.php, web/index_dev.php
After looking at the requirements for Apache in the htaccess file, we discovered that it would be pretty easy to just run with PHP's built-in web server for development.
=> Make it easier to use the PHP built-in web server.

classes/OpenCFP/Http/Controller/ProfileController.php, classes/OpenCFP/Http/Controller/SignupController.php
This PR
:bulb: `OpenCFP\ProfileImageProcessor` doesn't exist, but `OpenCFP\Domain\Services\ProfileImageProcessor` does.
=> Fix: Remove import for non-existent class

tests/OpenCFP/Application/SpeakersTest.php, tests/OpenCFP/Domain/Entity/FavoriteTest.php, tests/OpenCFP/Domain/Entity/Mapper/TalkTest.php, tests/OpenCFP/Domain/Entity/TalkTest.php, tests/OpenCFP/Http/API/ApiControllerTest.php, tests/OpenCFP/Http/API/ProfileApiControllerTest.php, tests/OpenCFP/Http/API/TalkApiControllerTest.php, tests/OpenCFP/Infrastructure/Crypto/PseudoRandomStringGeneratorTest.php, tests/unit/controllers/TalkControllerTest.php
=> Fix: Reduce visibility from public to protected

classes/OpenCFP/Application/Speakers.php, tests/OpenCFP/Application/SpeakersTest.php
=> Fix: Speaker::findProfile() doesn't accept any arguments

classes/OpenCFP/Application.php, classes/OpenCFP/Provider/YamlConfigDriver.php
See https://github.com/igorw/ConfigServiceProvider/pull/46
When the above PR is merged, we can revert this commit. The current code
is throwing errors in the test suite due to deprecation notices from Yaml::parse.
We haven't upgraded this package so no idea why we started getting notices like
this but it is what it is.
Parse method now triggers a warning if you give it a path. It expects the yaml file
contents, not a path. This patch adds a provider that extends Igor's and makes
this change. We then sub this provider into the ChainConfigProvider instead of
using SilexConfigServiceProvider's default.
---
What's odd about this is that I can't for the life of me find that error message in the version of  `symfony/yaml` we're using. I'm overlooking something, clearly... but this fixes the …
=> Resolve YAML::parse deprecation notice.

migrations/20150702132854_fix_defaults_for_users_table.php
When using more strict MySQL settings it is not possible to add records without specifying values for NOT NULL columns unless a default is specified. Phinx creates NOT NULL columns by default so many fields were giving us problems when trying to register a user without giving a proper value for many fields that the signup controller wasn't asking about.
This fixes the problem by altering the database schema such that the fields in question will either allow null values or specify a default value in the case that NULL is used or no value is provided.
For people with strict MySQL settings, this migration will most likely not be reversible as columns will end up with NULL values and reversing this migration results in making those columns NOT NULL.
People with less-strict MySQL settings will …
=> Fix defaults for users table.

templates/forms/_user.twig
The variable `preview_photo` is only generated in ProfileController and not in SignupController, but they both use forms/_user.twig
If you upload a user photo during signup and have a form error (like invalid password) it fails because `preview_photo` doesn't exist.
=> Uploading user photo and form error cause internal server error

.travis.yml
=> Fix: Cache directory for dependencies installed with Composer

.travis.yml, tools/travis/build.sh, tools/travis/reset-database.sh
=> Fix: Clean up Travis configuration and build script

.travis.yml
This PR
:information_desk_person: Following https://github.com/composer/composer/pull/4219, this will break the build if `composer.lock` is not up to date.
=> Enhancement: Run composer --validate on Travis

classes/Http/Controller/ForgotController.php
In 50d1ed25, @chartjes changed the no-matching-user message to be
ambiguous, but we are still using a positive message when the email does
exist, so we haven't closed the loop.
This PR changes to use the same message for both cases: attempted reset
of an unknown email, and reset of a known email.
=> Use ambiguous success message when reset-password works

classes/Http/Controller/ProfileController.php
As far as I can tell, the `user_edit` route was always wrong here; there's no reason we would want a form pointing at that route.
This is all in the controller, and there's no controller test at present; not sure whether I should set one up for this small degree of change?
=> Correct the route for profile update after invalid entry; fixes #214

classes/Console/Command/AdminDemoteCommand.php, classes/Console/Command/AdminPromoteCommand.php, classes/Http/Controller/ForgotController.php, classes/Infrastructure/Auth/SentryIdentityProvider.php
This PR
:information_desk_person: Alternatively, one could add the `unused_use` fixer in #242.
=> Fix: Remove unused imports

classes/Http/Controller/Admin/AdminAccessTrait.php, classes/Http/Controller/Admin/SpeakersController.php, classes/Http/Controller/Admin/TalksController.php, composer.json, composer.lock, tests/OpenCFP/Http/Controller/Admin/AdminAccessTraitFake.php, tests/OpenCFP/Http/Controller/Admin/AdminAccessTraitTest.php
This PR
Follows #249.
Related to #247.
=> Fix: Add coverage for AdminAccessTrait

composer.json, composer.lock, tests/OpenCFP/Http/Controller/FlashableTraitFake.php, tests/OpenCFP/Http/Controller/FlashableTraitTest.php
=> Fix: Add coverage for FlashableTrait

composer.json, composer.lock, tests/OpenCFP/ContainerAwareFake.php, tests/OpenCFP/ContainerAwareTest.php
=> Fix: Add coverage for ContainerAware

classes/Provider/SymfonySentrySession.php, tests/OpenCFP/Provider/SymfonySentrySessionTest.php
=> Fix: Cover SymfonySentrySession

composer.json, composer.lock, phpunit.xml.dist
This PR
:person_with_pouting_face: Looks like we're living on the edge, with a bunch of unbound version constraints?
```
$ vendor/bin/phpunit
PHPUnit 4.6.6 by Sebastian Bergmann and contributors.
Configuration read from /Users/am/Sites/opencfp/opencfp/phpunit.xml.dist
...............................................................  63 / 110 ( 57%)
...............................................
Time: 1.27 seconds, Memory: 84.25Mb
OK (110 tests, 168 assertions)
```
```
$ vendor/bin/phpunit
PHPUnit 4.8.6 by Sebastian Bergmann and contributors.
Runtime:	PHP 5.6.12 with Xdebug 2.3.3
Configuration:	/Users/am/Sites/opencfp/opencfp/phpunit.xml.dist
..............................................................................................................
Time: 1.26 seconds, Memory: 84.75Mb
OK …
```
=> Fix: Require more recent phpunit/phpunit

classes/Http/Controller/Admin/SpeakersController.php, templates/layouts/dashboard.twig
The speakers names in the admin speaker listing are displayed as full name (first last) format but are sorted on last name, causing some confusion when attempting to find the speakers in the list. I altered the order to be on firstname and it makes finding speakers much easier.
=> speakers list makes more sense alphabetized by first name

Makefile
This PR
Follows #242.
Run
```
$ make cs
```
=> Enhancement: Add Makefile with cs target

classes/Domain/Entity/Mapper/Talk.php, classes/Http/Controller/Admin/ReviewController.php
The missing alias, total_rating, was causing an uncaught exception. I'm assuming this snuck it from an old version of the application.
Also, I added the use of getId instead of just the id property for consistency sake.
=> Missing query alias

classes/Domain/Entity/Mapper/Talk.php, classes/Http/Controller/Admin/ReviewController.php, templates/admin/review/_table.twig
After all of the admins have gone through and gave either a positive or negative rating to the talks, there was no way to decide which talks had the highest ranting.  
Though the talks were in order from highest to lowest, if you wanted to cut it off at a particular point there was no way to know what that point was.  This pull request now provides a way for admins to see the rating for a given talk and how many people have rated it.
=> Adding the rating and the number of ratings to the Review Talks page

classes/Console/Command/AdminPromoteCommand.php
I fixed the issue in #272 by removing the "(or new)" parenthetical from the help text, so no future intrepid programmers will be tripped up by it again.
=> Fixes github issue #272: "bin/opencfp list" has inaccurate description for admin:promote

classes/Domain/Entity/Mapper/Talk.php, templates/admin/talks/_table.twig
* Clicking on column headings should sort the table by that column, but
it was passing in the column heading in the "sort" parameter instead
of the "order_by"
* The default sort order was DESC, which means string sorted Z-A.
Changed the default to ASC.
=> Fixes broken column sorting on admin/talks page.

.travis.yml
This PR
Related to #288.
:information_desk_person: There's no use for reporting coverage if the build failed, eh?
For reference, see https://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle.
=> Fix: Do not bother reporting coverage if the build failed

.travis.yml, composer.json, composer.lock
=> Fix: Require codeclimate/php-test-reporter:0.2.0

phpunit.xml.dist
This PR
See https://travis-ci.org/opencfp/opencfp/jobs/97889795#L493-L495:
```
Runtime:	PHP 5.5.21 with Xdebug 2.2.7
Configuration:	/home/travis/build/opencfp/opencfp/phpunit.xml.dist
Warning:	No whitelist configured for code coverage
```
=> Fix: Use a whitelist filter instead of blacklisting

.travis.yml
=> Fix: Run php-cs-fixer on PHP5.6 only

.editorconfig
This PR
Follows #227.
:information_desk_person: Throughout the project, YAML files are indented with 2 spaces. Since we're using `.editorconfig`, it makes sense to adjust it, as not to fight an IDE supporting it.
=> Fix: Set indent size to 2 for YAML files

templates/admin/talks/_table.twig
Per issue: https://github.com/opencfp/opencfp/issues/285
Sorting UI was removed and a different one added instead. I don't believe this was done on purpose, but merely product of an older version of OpenCFP being worked on. This PR re-adds the sort UI that has sort direction arrows.
Also, the up and down vote rating icons are being re-added in this PR.
=> Re-adding Sorting and Rating UI

.travis.yml
This PR
Related to #288.
:information_desk_person: This, of course, only gives us faster feedback if the build has failed.
=> Fix: Allow builds to finish early

.travis.yml
This PR
Related to #288.
:information_desk_person: If it doesn't get merged to `master`, we don't care, do we?
=> Fix: Only collect and report coverage on merge to master

.travis.yml
This PR
Related to #288.
:information_desk_person: We only need it when we want to collect coverage, right?
=> Fix: Disable xdebug when we don't need it

classes/Http/Controller/Admin/SpeakersController.php, classes/Http/Controller/Admin/TalksController.php, tests/OpenCFP/Http/Controller/Admin/SpeakersControllerTest.php, tests/OpenCFP/Http/Controller/Admin/TalksControllerTests.php
This PR applies a fix for these issues: https://github.com/opencfp/opencfp/issues/276 https://github.com/opencfp/opencfp/issues/277
If no record is found, the user is redirected to the index page with a flash error message.
=> Proper error message on not found speakers or talks

composer.json, composer.lock, tests/unit/controllers/SessionDouble.php, tests/unit/controllers/TalkControllerTest.php
This PR
Related to https://github.com/opencfp/opencfp/issues/308.
See https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-1-basic-coding-standard.md#3-namespace-and-class-names:
> This means each class is in a file by itself, and is in a namespace of at least one level: a top-level vendor name.
:information_desk_person: This could be part of a series cleaning up the general structure of existing tests.
=> Fix: Each class should be in a file of its own

classes/Http/Controller/Admin/AdminsController.php, classes/Http/Controller/Admin/DashboardController.php, classes/Http/Controller/Admin/ReviewController.php, classes/Http/Controller/Admin/SpeakersController.php, classes/Http/Controller/Admin/TalksController.php
This PR
:information_desk_person: Not sure how the routing and dispatching works, but I don't think that the actions dispatched to should be `private` or `protected`.
=> Fix: Increase visibility of actions

templates/admin/talks/view.twig, web/assets/css/site.css
This makes it easier to determine who wrote which comment. Currently, the only identifier of comment author is avatar. This PR addresses: https://github.com/opencfp/opencfp/issues/279
=> Add comment author full name to comment meta section

tests/OpenCFP/ContainerAwareTest.php
This PR
Follows https://github.com/opencfp/opencfp/pull/317#issuecomment-168337163.
:information_desk_person: Consistency always wins!
=> Fix: Use Mockery in ContainerAwareTest

tests/OpenCFP/Domain/Services/ResetEmailerTest.php, tests/OpenCFP/Http/Controller/Admin/SpeakersControllerTest.php, tests/OpenCFP/Http/Controller/Admin/TalksControllerTests.php
This PR
Related to #307.
:information_desk_person: For reference, see 
* [PHPUnit_Framework_TestCase::setUp()](https://github.com/sebastianbergmann/phpunit/blob/4.8/src/Framework/TestCase.php#L1905-L1911)
* [PHPUnit_Framework_TestCase::tearDown()](https://github.com/sebastianbergmann/phpunit/blob/4.8/src/Framework/TestCase.php#L1937-L1943)
=> Fix: Visibility should be protected

composer.json, composer.lock
This PR
Related to #307.
:information_desk_person: Because why not? [`fzaninotto/faker:1.2.0`](https://packagist.org/packages/fzaninotto/faker#v1.2.0) was released more than two years ago.
=> Fix: Update fzaninotto/faker

tests/OpenCFP/Util/Faker/GeneratorTest.php, tests/OpenCFP/Util/Faker/GeneratorTrait.php, tests/unit/TalkFormTest.php
This PR
Related to #307.
:information_desk_person: While I personally tend to use traits with care, this has proven useful in tests.
=> Enhancement: Extract GeneratorTrait

classes/Domain/Services/Login.php
=> Fix: Add missing docblocks to Domain\Services\Login

tests/OpenCFP/Infrastructure/Persistence/SpotSpeakerRepositoryTest.php
=> Fix: Cover Infrastructure\Persistence\SpotSpeakerRepository

tests/OpenCFP/Infrastructure/Persistence/SpotTalkRepositoryTest.php
=> Fix: Cover Infrastructure\Persistence\SpotTalkRepository

tests/OpenCFP/Infrastructure/Auth/SentryIdentityProviderTest.php
=> Fix: Cover Infrastructure\Auth\SentryIdentityProvider

.php_cs, classes/Http/Controller/ForgotController.php, tests/OpenCFP/ContainerAwareTest.php, tests/OpenCFP/Domain/Entity/Mapper/TalkTest.php, tests/OpenCFP/Http/Controller/FlashableTraitFake.php, tests/unit/controllers/SignupControllerTest.php
This PR
Follows #242.
:information_desk_person: See https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/1.11#usage:
> **unused_use [symfony]**
Unused use statements must be removed.
=> Enhancement: Enable unused_use fixer

tests/OpenCFP/Domain/Services/LoginTest.php, tests/OpenCFP/Infrastructure/Auth/SentryIdentityProviderTest.php, tests/OpenCFP/Infrastructure/Persistence/SpotSpeakerRepositoryTest.php
=> Fix: Use GeneratorTrait

tests/OpenCFP/Domain/Services/LoginTest.php
=> Fix: Use more appropriate formatter

tests/OpenCFP/Domain/Entity/FavoriteTest.php, tests/OpenCFP/Domain/Entity/Mapper/TalkTest.php, tests/OpenCFP/Domain/Entity/TalkTest.php, tests/OpenCFP/Http/API/ApiControllerTest.php, tests/OpenCFP/Http/API/ProfileApiControllerTest.php, tests/OpenCFP/Http/API/TalkApiControllerTest.php, tests/OpenCFP/Http/Controller/Admin/SpeakersControllerTest.php, tests/OpenCFP/Http/Controller/Admin/TalksControllerTests.php, tests/OpenCFP/Infrastructure/Crypto/PseudoRandomStringGeneratorTest.php, tests/unit/controllers/TalkControllerTest.php
This PR
Related to #307.
Follows #312.
=> Fix: Case-insensitive method names

tests/OpenCFP/Domain/Speaker/SpeakerProfileTest.php
This PR
Follows #326.
Follows #243.
:information_desk_person: This PR fixes the build failing after merging #326, see
* https://travis-ci.org/opencfp/opencfp/jobs/99910489#L531
=> Fix: Remove unused import

tests/OpenCFP/Domain/Speaker/SpeakerProfileTest.php
This PR
Follows #326.
:information_desk_person: This fixes the build failing after merging #326, see
* https://travis-ci.org/opencfp/opencfp/jobs/99910488#L527
=> Fix: Pick a number greater than 0, but not 1

tests/OpenCFP/Util/Faker/GeneratorTrait.php
This PR
:information_desk_person: This produces the same results, sort of.
For reference, see https://github.com/fzaninotto/Faker#seeding-the-generator.
=> Fix: Seed Faker

classes/Application.php
Yeahhhh... this is my bad so boo to me on this one.
In applying some fix-up changes to #333, I needed to get the exception message before error handler munched it. Rather than actually improving things (as I should have), I just dumped the message as a temporary measure. This got committed.
Because this was committed, the following happened afterwards...
That's right... the unit test suite is actually bailing in the middle of execution from a `die` statement in the error handler and then returning zero! 
Anywho, this PR is against the tip of `upstream/master` and demonstrates a passing (for real) test suite. Kicking myself over this. I should have caught it. My bad!
/cc @chartjes Can you review and merge this when ready?
=> Remove poor-man's debug statement

phpunit.xml.dist, tests/bootstrap.php
=> Fix: Simplify test bootstrapping

phpunit.xml.dist
=> Fix: Remove non-existent test suites

config/development.dist.yml, config/production.dist.yml, config/testing.yml, templates/_header.twig
One of the first things regular speakers look for on CFP page is the conference date and location. This PR replaces the text "For More Information About The Conference" with the text "GeeHCon is on 26/10/2014 to 31/10/2014 in Swansea, UK".
This only happens if the two new config values that are added are present, and so is backwards compatible.
The new config values are:
event_location - the location of the event in string format
date_format - a Twig `date()` filter compatible string to format the event dates
=> Added conference information from new config settings

templates/admin/talks/_table.twig, templates/admin/talks/view.twig
I'm looking at OpenCFP to help run the CFP at CascadiaFEST 2016 (CascadiaJS). I noticed that the admin talk vote icons didn't have explanations on them so I thought I'd add some simple titles. The copy is open for modifications, but I thought I'd at least start the conversation.
=> Add titles to talk voting icons

classes/Http/Form/SignupForm.php, tests/Http/Form/SignupFormTest.php, tests/Infrastructure/Persistence/IlluminateAirportInformationDatabaseTest.php
Related: #352 
@madasha added a validation check to ensure speaker photo upload was valid but was not comfortable adding tests for this feature. I've got that covered in this PR.
Original PR:
```
madasha commented 3 days ago
I ran into the following problem setting up opencfp for Bulgaria PHP:
When registering a new speaker profile or updating the speaker profile picture the following behaviour is observed if the file upload limit in php.ini is lower than the 5MB limit set in the code: Instead of showing a file upload error in the form, the application would throw a '500 Internal Server error' into the index page, where it redirects the user as a side effect of handling a file upload exception.
I added a few lines to classes/Http/Form/SignupForm.php, utilizing the functionality of …
```
=> Add unit tests to work started in #352

classes/Domain/Entity/Mapper/Talk.php, classes/Http/Controller/SecurityController.php, classes/Http/Controller/TalkController.php, tests/Domain/Entity/Mapper/TalkTest.php, tests/Http/Controller/SignupControllerTest.php, tests/Http/Controller/TalkControllerTest.php
=> Fix: Remove unused local variables

tests/Domain/Entity/Mapper/TalkTest.php
=> Fix: Remove an unused private method

classes/Http/Controller/Admin/AdminAccessTrait.php, classes/Http/Controller/Admin/ExportsController.php, classes/Http/Controller/Admin/SpeakersController.php, classes/Http/Controller/Admin/TalksController.php, tests/Http/Controller/Admin/AdminAccessTraitFake.php
=> Fix: Remove unused parameter

tests/Domain/Services/ResetEmailerTest.php
=> Fix: Add missing docblocks

tests/DatabaseTestCase.php, tests/Domain/Entity/TalkTest.php, tests/Domain/Services/ResetEmailerTest.php, tests/Infrastructure/Persistence/IlluminateAirportInformationDatabaseTest.php
=> Fix: Namespace doesn't match project structure

.travis.yml
This PR
Related to https://github.com/opencfp/opencfp/pull/357/files#r54354143.
:information_desk_person: We're using that option in [`Makefile`](https://github.com/opencfp/opencfp/blob/master/Makefile#L4), and using it on Travis at least helps to see what the actual problem is when the build fails due to CS issues.
=> Fix: Run php-cs-fixer with --diff on Travis

.travis.yml, CONTRIBUTING.md, Makefile, config/testing.yml, phinx.yml.dist
This PR
:information_desk_person: Run
```
$ make
```
to run all the things!
=> Enhancement: Streamline testing process

classes/Application.php, config/development.dist.yml, config/production.dist.yml
Allows users to specify their default timezone via config files. The value is stored in `application.date_timezone` and is set in the application as the last step in `__construct`.
Normally this is set on the server side in `php.ini` files, so no worries if you don't want to merge this. I could see value (especially on shared servers) in having this be configurable app-side so I wanted to suggest & provide a pr for it.
I'm not sure if any tests need to be added to this? I'm happy to add them if needed. Also totally happy to move things around if they would go in better places.
=> Add timezone to .yml config files

.editorconfig
=> Fix: Allow to indent Makefile with tabs

templates/admin/speaker/index.twig, templates/admin/speaker/view.twig
While using the software I found this great functionality to check airfare cost for speakers flying in from somewhere through google flights. There was only a minor problem - the value passed to the 'f' param in the URL is supposed to be the code of the airport, instead of the full name to make it work. Like this:
https://www.google.com/flights/#search;f=BRU;t=SOF;d=2016-10-07;r=2016-10-09
Made a minor change in two templates in the admin area to reflect this in the composed URL.
=> Changing value passed to google flights URL to match airport code

classes/Console/Command/AdminDemoteCommand.php, classes/Console/Command/AdminPromoteCommand.php
This PR
Related to #380.
:information_desk_person: Not sure if it hasn't always been that way, but one is supposed to return either `null` or an `int` from `execute()`.
=> Fix: Return error codes instead of exiting with 1

classes/Console/Command/AdminDemoteCommand.php, classes/Console/Command/AdminPromoteCommand.php, classes/Console/Command/ClearCacheCommand.php
This PR
:information_desk_person: No need to repeat what is automatically inherited from the parent. As a heads-up, this can be part of a series cleaning up console commands!
=> Fix: Remove useless docblocks

tests/Http/Controller/SignupControllerTest.php
This PR
Somewhat related to #378.
=> Fix: Actually mock Spot\Locator

classes/Http/Controller/Admin/AdminsController.php, classes/Http/Controller/Admin/DashboardController.php, classes/Http/Controller/Admin/ExportsController.php, classes/Http/Controller/Admin/ReviewController.php, classes/Http/Controller/Admin/SpeakersController.php, classes/Http/Controller/Admin/TalksController.php, classes/Http/Controller/PagesController.php, classes/Http/Controller/ProfileController.php, classes/Http/Controller/SignupController.php, classes/Http/Controller/TalkController.php, classes/Provider/ApplicationServiceProvider.php, classes/Provider/Gateways/OAuthGatewayProvider.php, tests/Domain/Entity/FavoriteTest.php, tests/Domain/Entity/Mapper/TalkTest.php, tests/Domain/Entity/TalkTest.php, tests/Http/Controller/TalkControllerTest.php
=> Fix: Introduce explaining variable when fetching Spot\Locator from container

tests/Http/Controller/DashboardControllerTest.php, tests/Http/Controller/SignupControllerTest.php, tests/Http/Controller/TalkControllerTest.php
This PR
Somewhat related to #376.
=> Fix: Actually mock Sentry

classes/Console/Command/AdminDemoteCommand.php, classes/Console/Command/AdminPromoteCommand.php, classes/Http/Controller/Admin/AdminAccessTrait.php, classes/Http/Controller/Admin/AdminsController.php, classes/Http/Controller/Admin/DashboardController.php, classes/Http/Controller/Admin/ExportsController.php, classes/Http/Controller/Admin/ReviewController.php, classes/Http/Controller/Admin/TalksController.php, classes/Http/Controller/ForgotController.php, classes/Http/Controller/ProfileController.php, classes/Http/Controller/SecurityController.php, classes/Http/Controller/SignupController.php, classes/Http/Controller/TalkController.php, classes/Provider/ApplicationServiceProvider.php, classes/Provider/Gateways/OAuthGatewayProvider.php, classes/Provider/Gateways/WebGatewayProvider.php, tests/Http/Controller/DashboardControllerTest.php, tests/Http/Controller/TalkControllerTest.php
=> Fix: Introduce explaining variable when fetching Sentry from container

classes/Application.php, classes/Http/Controller/BaseController.php, classes/Http/Controller/TalkController.php, classes/Http/OAuth/AuthorizationController.php, classes/Provider/Gateways/WebGatewayProvider.php, classes/Provider/ResetEmailerServiceProvider.php, classes/Provider/TwigServiceProvider.php, tests/Http/Controller/Admin/TalksControllerTest.php, tests/Http/Controller/DashboardControllerTest.php
This PR
:information_desk_person: This allows to provide an inline docblock, which is helpful with 
* auto-completion
* reducing errors related to undefined methods when running inspections
* finding usages
and it also micro-optimizes the application, yay!
:person_with_pouting_face: In related news, I'm happy to sort out a few more of these issues. Also, noted that there are a bunch of different ways of fetching services from the container
* sometimes using the `ContainerAware` trait in controllers, services are fetched from the field `$app`
* sometimes using the `ContainerAware` trait in controllers, services are fetched using the method `service()`
* sometimes the container is passed into a controller action
What do you think, would it be worth to streamline this?
=> Fix: Introduce explaining variable when fetching Twig_Environment from container

tests/Console/ApplicationTest.php
This PR
Follows https://github.com/opencfp/opencfp/pull/380.
=> Fix: Cover Console\Application

tests/Http/Controller/DashboardControllerTest.php
=> Fix: Undefined class

classes/Console/Command/AdminDemoteCommand.php, classes/Console/Command/AdminPromoteCommand.php
This PR
Follows #380.
💁There's probably no need to extend the `try` and `catch` block further than trying to find a user, especially if we're only catching `UserNotFoundException`s.
=> Fix: Do not try too much

classes/Console/Command/AdminDemoteCommand.php, classes/Console/Command/AdminPromoteCommand.php, classes/Console/Command/ClearCacheCommand.php
=> Enhancement: Use SymfonyStyle to streamline console output

classes/Provider/Gateways/WebGatewayProvider.php, classes/Provider/TwigServiceProvider.php
This PR resolves an unreported error when requesting a page that does not exist. I noticed this messing around with the Sunshine PHP CFP site. There are two Twig globals registered in a before handler: `cfp_open` and `current_page`. When an exception happens in the routing layer, it looks like before middlware are not executed. This causes Twig to throw an exception when attempting to render the 404 page because neither of these globals are registered.
I moved them outside the before handler into the `TwigServiceProvider`. Additionally, I had to lazy-load the `current_page` value because `Request` is not available outside a web request in Silex. This way, we can register the global and it resolves at runtime in the correct context.
Before:
After:
=> Move globals registration to not fight with exception handler

classes/Application.php, classes/Provider/YamlConfigDriver.php, composer.json, composer.lock
This PR removes a dependency on the `ConfigServiceProvider` we use from https://github.com/igorw/ConfigServiceProvider. The service provider's main feature is its ability to load prefixed configuration from multiple formats given a configuration path to load. It also enabled self-referencing replacements using `%replacement%` syntax. We currently only support one format, YAML, and only one configuration file is ever loaded at a time. We have not had a reason to use replacements thus far.
We're removing this because the provider is *barely* incompatible with Silex 2.0 (some typehints need to be changed, basically) and PRs to the repository seem unmanaged.
```
/**
* Replace reference to `ChainConfigDriver` with `null` when PR below is merged.
* Symfony's YAML package deprecated allowing a …
```
=> Remove `igorw/config-service-provider`

README.md, classes/Console/Application.php, classes/Console/Command/UserCreateCommand.php, migrations/20150702132854_fix_defaults_for_users_table.php, tests/Console/ApplicationTest.php
Add ability to create a user from the command line.  It also has a flag to auto promote to admin.
bin/opencfp user:create --first_name=Brian --last_name=Retterer --email="bretterer@gmail.com" --password="123456abcdef" --admin
Fixes #274
=> user:create command 

classes/Domain/Entity/Mapper/Talk.php, migrations/20150702132854_fix_defaults_for_users_table.php
In the TopRatedByUserId query, the default order_by was set to rating, but the column was named review_count.
Fixes #407 
(migrations updated as a result of merging upstream into my branch)
=> Update default order by for review

classes/Domain/Entity/Mapper/Talk.php, templates/layouts/admin.twig
This PR
Previous behaviour only listed out positive votes on a talk; showing the total vote count as equal to the rating. This could lead to erroneous results. The new behaviour only filters our talks after the rating has been totalled, so that negative votes affect the result and ratings count as well.
Fixes #391.
=> Fixes #391

classes/Console/Command/AdminPromoteCommand.php, tests/Console/AdminPromoteCommandTest.php
Only the configure method had coverage before.
r? @mdwheele
=> Tests for AdminPromoteCommand to provide 100% coverage

templates/_header.twig
This PR resolves the issue #426 
If the date is already a DateTime object, and if you want to keep its current timezone, pass false as the timezone value : http://twig.sensiolabs.org/doc/filters/date.html#timezone
=> Fix arrival and departures displayed dates in the header

classes/Domain/Entity/Mapper/Talk.php
The not rated talks attempts to create a left join but in the where
statement attempts to look at the admin user id.  Unfortunately, this
will cause any talks that are not yet in talk_meta with the admin user
id to not be found.
The proper join query includes the admin user id as that is what you are
attempting to key off of rather than in the where portion of the query.
This will resolve where the talk does not yet exist in talk_meta and
will provide not yet rated talks properly in the admin area.
=> Not Rated Talks Query is Incorrect

.php_cs, .travis.yml, classes/Console/Command/UserCreateCommand.php, composer.json, composer.lock
This PR
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/compare/v1.11.2...v2.0.0.
=> Enhancement: Update friendsofphp/php-cs-fixer

tests/Domain/Entity/TalkTest.php
=> Fix: Use assertCount() instead of assertTrue()

classes/Console/Application.php, tests/Console/ApplicationTest.php
=> Fix: Remove accessor only used in test

composer.json
This PR
Not exactly related to #433.
=> Fix: Keep require and require-dev sections close to each other

classes/Console/BaseCommand.php
=> Fix: Class should probably be abstract

web/assets/js/admin/talk.js
This PR
Rationale: for [our event](http://apply.wp-europe.org/) we would like to split scoring the talks – some people only rate development talks, some people only rate development ones, etc. Sometimes, however, we rate the wrong talk, one that we shouldn't have rated at all and being able to remove the rating would be super nice.
=> Remove rating when repeatedly clicking thumbs up/down

composer.lock
Context: there was a missing property in a twig template and Spot was trying to throw `BadMethodCallException`, however the class wasn’t declared. It was [fixed some time ago](https://github.com/vlucas/spot2/commit/0c5baa035f90f34434e10cac0e1cf53f90d1408e#diff-d1cd5c83ba49d43232655b056fad3936R4), so we should update to a newer version.
Since we were depending on `dev-master` the easiest way to update Spot 2
was to update all dependencies via `composer update`.
Tests pass and I tested the main flows – registration, posting a new talk, voting, they all seem to work.
This PR
=> Fix missing `BadMethodCallException` by updating Spot 2 dependency

templates/admin/talks/view.twig
If a user doesn’t have a photo we are getting a Twig exception when trying to view their comments below a talk:
```
An exception has been thrown during the rendering of a template
("Method Spot\Relation\BelongsTo::photo_path does not exist")
```
This PR
=> Account for possibly missing `photo_path`

classes/Provider/Gateways/RequestCleaner.php
This PR 
The introduced code revokes the encoding of the three characters after sanitization.
Fixes #444.
=> Fixes double encoding of &, < and >

classes/Http/Controller/DashboardController.php, classes/Http/Controller/SignupController.php, classes/Http/Controller/TalkController.php, classes/Provider/TwigServiceProvider.php, composer.lock, templates/_header.twig, tests/Http/Controller/DashboardControllerTest.php
This PR moves calls from ```strtotime``` to ```DateTime```.
Additionally the configuration entry ```enddate``` can now be used to also add a time when the CfP ends. You should then also adapt the ```date_format``` to include the time. When no time is given in the config-value the current behaviour is used to let the CfP run until 23:59 of the given day. 
> Note: The CFP will still end 59 seconds before midnight!
Fixes #450.
=> fix enddate

README.md
Update the requirements section to specify installing the PHP7+ `intl` extension (same version as the minimum requirement for PHP).
`php7.0-intl` is the name of the package in *Debian Testing* and *Ubuntu 16.04+*, I assumed these were the target platforms, please correct me if I'm wrong.
=> Update Requirements Section in README

classes/Http/Form/Login.php, classes/Http/Form/ResetForm.php, tests/Http/Form/Entity/LoginTest.php, tests/Http/Form/Entity/ProfileTest.php, tests/Http/Form/Entity/UserTest.php, tests/Http/Form/LoginTest.php, tests/Http/Form/ResetFormTest.php, tests/Http/Form/TalkFormTest.php
This PR
*  	Completes the Login form tests 
*  	Creates the ResetForm tests and modifies the ResetForm class 
*  	Creates the tests for the OpenCFP/Http/Form/Entity/Login class
*  	Creates the tests for the OpenCFP/Http/Form/Entity/Profile class
*  	Creates the tests for the OpenCFP/Http/Form/Entity/User class
* 	Modifies the TalkForm test class
Follows N/A.
Related to N/A.
Fixes N/A.
=> Adds a few more unit tests

classes/Domain/AirportInfo.php, classes/Environment.php, classes/Http/Form/Form.php
=> Fix: Use null coalescing operator where possible

.php_cs, classes/Application.php, classes/Domain/Entity/Mapper/Talk.php, classes/Domain/Entity/User.php, classes/Domain/Services/Login.php, classes/Http/API/ApiController.php, classes/Http/Controller/Admin/ExportsController.php, classes/Http/Controller/Admin/SpeakersController.php, classes/Http/Controller/Admin/TalksController.php, classes/Http/Controller/ForgotController.php, classes/Http/Controller/ProfileController.php, classes/Http/Controller/SignupController.php, classes/Http/Controller/TalkController.php, classes/Http/Form/SignupForm.php, classes/Http/Form/TalkForm.php, tests/Domain/Entity/Mapper/TalkTest.php, tests/Domain/Entity/TalkTest.php, tests/Http/Controller/Admin/TalksControllerTest.php, tests/Http/Controller/SignupControllerTest.php, tests/Http/Controller/TalkControllerTest.php, tests/Http/Form/SignupFormTest.php, tests/Http/Form/TalkFormTest.php
This PR
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/v2.1.0#usage:
> **single_quote [`@Symfony`]**
Convert double quotes to single quotes for simple strings.
=> Enhancement: Enable single_quote fixer

bin/opencfp
Given that the -e option for specifying the environment
in which the command should run is not documented any where,
we remove it.
This way it won't clash any more with the user:create command
and specifying the email of the new user with -e.
Fixes #471
=> Remove -e as an environment option

classes/Provider/HtmlPurifierServiceProvider.php
The app has a reusable method that tells us where
HTML Purifier should put the cache files.
Use it instead of trying to get the cache path from the config.
Fixes #472
=> Get path to HTML Purifier cache from app

classes/Http/Controller/TalkController.php
The ORM returns `1` on successful updates which was used as the talk ID (sic!). I've fixed the bug for updates and unified the code for new talk creations.
Fixes #481
=> Pass proper talk ID to e-mail handler

classes/Application.php
This shows the correct path of the configuration file which couldn't be found.
=> print correct not-found filename on error

classes/Http/Form/SignupForm.php, tests/Http/Controller/SignupControllerTest.php
Changed the check for the joind.in url so users are now allowed to sign up with either a valid url or no url at all.
Fixes #491.
=> Allow sign up without joind.in url

classes/Http/Form/SignupForm.php, tests/Http/Form/SignupFormTest.php
My first name is Kévin (notice the `é`), and currently I cannot register on OpenCFP. This PR handles first names like last names, and will allow people with non-english characters in their names to submit CFPs with their real names.
=> Allow first names containing non-english chars

templates/admin/speaker/view.twig
This will allow an admin to see the additional notes from a speaker, if they are set.
Fixes #496 .
=> Add speaker notes to the speaker profile

.php_cs, classes/Http/Form/SignupForm.php, classes/Infrastructure/Persistence/SpotSpeakerRepository.php, classes/Provider/ControllerResolver.php, classes/Provider/Gateways/ApiGatewayProvider.php, classes/Provider/Gateways/OAuthGatewayProvider.php, composer.json, composer.lock
This PR
Follows https://github.com/opencfp/opencfp/pull/500#pullrequestreview-67378081.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer#usage:
>**yoda_style** [`@Symfony`]
>
>Write conditions in Yoda style (`true`), non-Yoda style (`false`) or ignore those conditions (`null`) based on configuration.
>
>
>- `equal` (`bool`, `null`): style for equal (`==`, `!=`) statements; defaults to `true`
>- `identical` (`bool`, `null`): style for identical (`===`, `!==`) statements; defaults to `true`
>- `less_and_greater` (`bool`, `null`): style for less and greater than (`<`, `<=`, `>`, `>=`) statements; defaults to `null`
=> Enhancement: Enable yoda_style fixer and enforce non-yoda-style comparisons

classes/Domain/Model/Talk.php, classes/Domain/Model/TalkMeta.php, classes/Http/Controller/Admin/DashboardController.php, tests/DatabaseTestCase.php, tests/Domain/Model/TalkTest.php, tests/Http/Controller/Admin/DashboardControllerTest.php
Related to #506.
This PR replaces all usage of spot in the admin dashboard controller with Illuminate Database models.
It also adds tests for this controller, and for the home made functions in the models.
Some small things besides that:
* Removed the Request object from the index function, since that was not used.
* Added an empty ```$guarded``` array to some models, so we can use the create() functionality.
To use the beginTransaction and rollBack functions you need to do so on the Capsule object in order for it to work
=> Use Illuminate Database for the admins dashboard controller

classes/Domain/Services/Authentication.php, classes/Domain/Services/TalkRating/TalkRatingException.php, classes/Domain/Services/TalkRating/TalkRatingStrategy.php, classes/Domain/Services/TalkRating/YesNoRating.php, classes/Http/Controller/Admin/ExportsController.php, classes/Http/Controller/Admin/TalksController.php, classes/Infrastructure/Auth/SentryAuthentication.php, tests/Domain/Services/TalkRating/YesNoRatingTest.php, tests/Http/Controller/Admin/TalksControllerTest.php
Playing with some options around talk ratings for #415 and #485 this is an initial refactor which removes the rating logic into a service class.
This piece of functionality is self contained and I'm going to suggest merging it, as the work going on around the migration away from spot my break the code.
This does introduce a minor bc break; the authentication interface gained a new method userId as a shortcut for retrieving the logged in user's id. This only presents a problem to people who've built their own authentication layer as a replacement to sentinel.
Further work required: (Future PR's)
- service locate the constructed strategy instead of calling new in the controller
- produce a similar service pattern for rendering the rating widget + rating score
- might also require some work …
=> Initial refactor to use a strategy class for handling ratings

classes/Http/Controller/SecurityController.php
A failed login was not catching all the exceptions correctly and thus throwing a 500 error instead of a nice error message; this fixes that problem
=> Failed login throws 500 error

classes/Provider/Gateways/WebGatewayProvider.php, classes/Provider/TwigServiceProvider.php, templates/layouts/admin.twig, templates/layouts/dashboard-nowrap.twig, templates/layouts/dashboard.twig, templates/layouts/default.twig
This PR
I'm working on a Sass-based restyling of the application and in the process of simplifying our templates / markup, came across this bug present on `master`.
**Before**
**After**
=> Fix active navigation class

classes/Http/Controller/Admin/ExportsController.php
**Steps required to reproduce the problem**
1. Create a talk
2. Make the description an excel executable formula like =2+3
3. Export csv of talks
**Expected Result**
* The cell with the talk description displays =2+3
**Actual Result**
* The cell displays 5
This particular instance isn't anything bad, but as detailed here: https://www.contextis.com/blog/comma-separated-vulnerabilities this could be used for all sorts of malpractice.
This fixes the issue by adding a ' in front of all cells that start with any of  ```= - + @``` to stop the formulas from executing
cc: @chartjes
=> Fix csv issues

classes/Domain/Entity/Mapper/Talk.php, classes/Domain/Model/Talk.php, classes/Domain/Services/TalkFormat.php, classes/Domain/Services/TalkFormatter.php, classes/Domain/Talk/TalkFormatter.php, classes/Http/Controller/Admin/DashboardController.php, tests/Domain/Model/TalkTest.php, tests/Domain/Services/TalkFormatterTest.php, tests/Http/Controller/Admin/DashboardControllerTest.php
This PR moves the createdFormattedOutput function of the model to another class. The version in the talk mapper still exists, but is just used to point to the new function.
I moved the function to a new location in order to keep the models clean, and a bit of separation of concerns. I'm not 100% sure on the names of the class and interface, so feedback is welcome.
I also changed the scopeRecent a little bit to now just return a builder object instead of the formatted array. This is in line with how scopes are intended, and would allow us to chain multiple scopes if so desired.
Related to #506 .
=> Move talk formatting to a new class

.php_cs, classes/Console/Command/UserCreateCommand.php, classes/Http/Controller/SignupController.php, classes/Http/Controller/TalkController.php, tests/Domain/Model/TalkTest.php, tests/Http/Controller/ProfileControllerTest.php, tests/Http/Controller/SignupControllerTest.php, tests/Http/Controller/TalkControllerTest.php
This PR
Somewhat related to #514.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/v2.7.1#usage:
>**no_extra_consecutive_blank_lines** [`@Symfony`]
>
>Removes extra blank lines and/or blank lines following configuration.
>
>
>* `tokens` (`array`): list of tokens to fix; defaults to `['extra']`
=> Enhancement: Enable no_extra_consecutive_blank_lines fixer

.travis.yml
This PR
💁‍♂️ For reference, see
* https://travis-ci.org/opencfp/opencfp/builds/288589424#L459-L462
* https://travis-ci.org/opencfp/opencfp/builds/288589424#L493-L495
❗️ There were times when the run of `composer self-update` on Travis CI would **not** update to the latest stable version, but these times are over, hehe.
=> Fix: Update composer itself once only

classes/Provider/Gateways/WebGatewayProvider.php
Before this, if the route the user requested wasn't defined, it would
cause an error in the 404 page, as it didn't go through the before
functions.
This commit fixes that by first of all binding it to app, instead of web
so it checks in all routes, even if it doesn't match the web, or any
route we know. It also makes it an Early event, which means that it will
fire off, even if its a 404.
**Old version**
=> Fix twig errors on non existent route

classes/Application.php, classes/Domain/Model/TalkMeta.php, classes/Domain/Services/TalkRating/TalkRating.php, classes/Domain/Services/TalkRating/TalkRatingContext.php, classes/Domain/Services/TalkRating/TalkRatingStrategy.php, classes/Domain/Services/TalkRating/YesNoRating.php, classes/Http/Controller/Admin/TalksController.php, classes/Provider/TalkRatingProvider.php, tests/Domain/Services/TalkRating/YesNoRatingTest.php
This PR does a few things:
1. Create a TalkRating base class which has some standard functionality like saving the new rating.
2. Create a TalkRatingContext, which defines what strategy to use
3. Create a Provider which calls the TalkRatingContext
4. Override some standard Illuminate functionality in relation to created at and updated at functions.
Follows #503 .
=> Refactor of Talk Rating

.php_cs, classes/Domain/Model/Talk.php, classes/Domain/Services/TalkFormat.php, classes/Domain/Services/TalkRating/TalkRatingContext.php, classes/Domain/Talk/TalkFormatter.php
This PR
Somewhat related to https://github.com/opencfp/opencfp/pull/523.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/v2.7.1#usage:
>**return_type_declaration** [`@Symfony`]
>
>There should be one or no space before colon, and one space after it in return type declarations, according to configuration.
>
>
>* `space_before` (`'none'`, `'one'`): spacing to apply before colon; defaults to `'none'`
💡 Note that [`PSR-12`](https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md#44-methods-and-functions), which has some ideas about spacing around the `:`, is a work in progress. Nonetheless, by enabling the fixer here, we default to no space before the `:`, as suggested by PSR-12 as well.
=> Enhancement: Enable return_type_declaration fixer

.travis.yml
This PR
Follows #518.
💁‍♂️ For reference, see https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn.
=> Enhancement: Enable caching for yarn on Travis

.travis.yml
This PR
Somewhat related to #526.
💁‍♂️ The environment variable `WITH_COVERAGE` (previously used for indicating the desire to collect code coverage) is actually never used, but a variable `COLLECT_COVERAGE` is set in the `before_script` section, so I remove the former and rename the latter here.
=> Fix: Conditions for collection coverage

.php_cs, classes/Console/Application.php, classes/Domain/Entity/Tag.php, classes/Domain/Entity/TalkTag.php, classes/Domain/Speaker/SpeakerRepository.php, classes/Domain/Talk/TalkRepository.php, classes/Environment.php, classes/Http/Form/ForgotForm.php, classes/Http/Form/Form.php, classes/Http/Form/ResetForm.php, classes/Provider/CallForProposalProvider.php, classes/Provider/CiconiaEngine.php, classes/Provider/ControllerResolver.php, classes/Provider/ControllerResolverServiceProvider.php, classes/Provider/DatabaseServiceProvider.php, classes/Provider/HtmlPurifierServiceProvider.php, classes/Provider/SentryServiceProvider.php, classes/Provider/TwigServiceProvider.php
This PR
Related to https://github.com/opencfp/opencfp/pull/529#issuecomment-342521923.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/v2.7.1#usage:
>**blank_line_after_opening_tag** [`@Symfony`]
>
>Ensure there is no code on the same line as the PHP open tag and it is followed by a blank line.
=> Enhancement: Enable blank_line_after_opening_tag fixer

tests/Http/API/ApiControllerTest.php, tests/Http/API/ProfileApiControllerTest.php, tests/Http/API/TalkApiControllerTest.php
=> Fix: Use constants for HTTP response status codes

phpunit.xml.dist
=> Fix: Reference phpunit.xsd using relative path

README.md
This PR
💁‍♂️ It's painfully slow, and running `npm install` rather than running `yarn install` with a checked in `yarn.lock` will eventually produce different results (as `npm` doesn't take into account locked dependencies in `yarn.lock`).
=> Fix: Suggest to use yarn (rather than npm)

.travis.yml
This PR
💁‍♂️ For reference, see https://docs.travis-ci.com/user/build-stages. The advantage of using stages is this:
* builds are executed stage by stage, but subsequent stages are only executed if builds for prior stages passed (if coding standard checks failed, we don't need to even worry about tests)
* we can fine-tune each stage for the desired steps
* we can add more stages (for example, for compiling assets to see if these even compile)
=> Enhancement: Use stages on Travis

classes/Http/Controller/ProfileController.php, classes/Http/Controller/TalkController.php, classes/Infrastructure/Auth/SpeakerAccess.php, classes/Provider/Gateways/WebGatewayProvider.php, tests/Infrastructure/Auth/SpeakerAccessTest.php
This PR moves some standard auth checks to middleware
In a lot of the speaker controllers, the first thing every functions did was the following check:
```php
if (!$auth->check()) {		
return $this->redirectTo('login');		
}
```
This moves all the those checks to one central point, the ```SpeakerAccess```  Class, which gets called before the controller is executed.
I didn't add this to all the speaker controllers, since some of them keep the check in other places, and i didn't want to mess with that logic for now.
=> Enhancement: Move auth checks to middleware

.php_cs, classes/Application/Speakers.php, classes/Domain/CallForProposal.php, classes/Domain/Model/Airport.php, classes/Domain/Services/TalkRating/YesNoRating.php, classes/Domain/Speaker/SpeakerProfile.php, classes/Domain/Talk/TalkSubmission.php, classes/Http/Form/Form.php, classes/Http/Form/SignupForm.php, classes/Http/Form/TalkForm.php, tests/TestCase.php
This PR adds return types to a lot of functions. Functions that could also return null/ other types of responses haven't been updated.
It also forces some types on parameters where possible. And updates some docblocks
=> Enhancement: Return types and general clean up

.php_cs, tests/Application/SpeakersTest.php, tests/Domain/Model/AirportTest.php, tests/Domain/Talk/TalkSubmissionTest.php, tests/EnvironmentTest.php, tests/Http/API/ApiControllerTest.php, tests/Infrastructure/Auth/SentryIdentityProviderTest.php, tests/Infrastructure/Persistence/SpotSpeakerRepositoryTest.php
This PR
>**php_unit_expectation** [@PHPUnit52Migration:risky, @PHPUnit54Migration:risky, @PHPUnit56Migration:risky, @PHPUnit57Migration:risky, @PHPUnit60Migration:risky]
>
>Usages of `->setExpectedException*` methods MUST be replaced by `->expectException* methods`.
>
>Risky rule: risky when PHPUnit classes are overridden or not accessible, or when project has PHPUnit incompatibilities.
>
>
>* `target` (`'5.2'`, `'5.6'`, `'newest'`): target version of PHPUnit; defaults to `'newest'`
and
>**php_unit_no_expectation_annotation** [@PHPUnit32Migration:risky, @PHPUnit35Migration:risky, `@PHPUnit43Migration:risky, @PHPUnit48Migration:risky, @PHPUnit50Migration:risky, …
=> Enhancement: Enable php_unit_expectation and php_unit_no_expectation_annotation fixers

.php_cs
=> Fix: Remove duplicate key from php-cs-fixer configuration

tests/Application/SpeakersTest.php, tests/Domain/Model/AirportTest.php, tests/Domain/Talk/TalkSubmissionTest.php, tests/EnvironmentTest.php, tests/Http/API/ApiControllerTest.php, tests/Infrastructure/Auth/SentryIdentityProviderTest.php, tests/Infrastructure/Persistence/SpotSpeakerRepositoryTest.php
This PR
Follows #549.
💁‍♂️ For reference, see https://thephp.cc/news/2016/02/questioning-phpunit-best-practices.
=> Fix: Move expectations in regard to exceptions

tests/Infrastructure/Auth/AdminAccessTest.php, tests/Infrastructure/Auth/SpeakerAccessTest.php
This PR
💁‍♂️ Test methods are already prefixed with `test`.
=> Fix: Remove useless annotation

.codeclimate.yml
This PR adds the PHPMD option to code climate. 
This should be useful to give more insight into where faults within the code base are, and give better insight in what future PR's do to the complexity of the code base.
For more info see: https://docs.codeclimate.com/docs/phpmd, and the PHPMD documentation https://phpmd.org/
=> Enhancement: PHP Mess Detector for Code Climate

.travis.yml, composer.json, composer.lock
=> Fix: Remove codeclimate/php-test-reporter

.php_cs, classes/Domain/Entity/Mapper/Talk.php, classes/Domain/Entity/Mapper/User.php, classes/Domain/Entity/User.php, classes/Domain/Services/ResetEmailer.php, classes/Domain/Speaker/SpeakerRepository.php, classes/Domain/Talk/TalkFormatter.php, classes/Environment.php, classes/Http/Controller/Admin/TalksController.php, classes/Http/Controller/FlashableTrait.php, classes/Http/Controller/ProfileController.php, classes/Http/Controller/TalkController.php, classes/Http/Form/Form.php, classes/Http/Form/SignupForm.php, classes/Provider/ControllerResolver.php, tests/Http/Controller/TalkControllerTest.php, tests/Http/Form/TalkFormTest.php
This PR
>**phpdoc_align** [`@Symfony`]
>
>All items of the given phpdoc tags must be aligned vertically.
>
>
>* `tags` (`array`): the tags that should be aligned; defaults to `['param', 'return', 'throws', 'type', 'var']`
=> Enhancement: Enable phpdoc_align fixer

classes/Domain/Services/ProfileImageProcessor.php, classes/Http/Controller/ProfileController.php, tests/Http/Controller/ProfileControllerTest.php, tests/WebTestCase.php
This PR refactors the profile process action, and its tests.
* The tests are now based on the WebTestCase, and are a lot more readable.
* Added an asLoggedInSpeaker function to WebTestCase
* Some functionality got extracted to new functions
* Put the profile image processor in charge of naming the new file.
* Use illuminate instead of spot
=> Refactor: profile process action

.php_cs, classes/Application.php, classes/Domain/CallForProposal.php, classes/Domain/Entity/Mapper/Talk.php, classes/Domain/Entity/Mapper/User.php, classes/Domain/Talk/TalkFormatter.php, classes/Http/Controller/TalkController.php, classes/Http/Form/Form.php, classes/Http/Form/SignupForm.php, classes/Http/Form/TalkForm.php, tests/Http/Form/SignupFormTest.php, tests/Http/Form/TalkFormTest.php
This PR
>**phpdoc_scalar** [`@Symfony`]
>
>Scalar types should always be written in the same form. `int` not `integer`, `bool` not `boolean`, `float` not `real` or `double`.
=> Enhancement: Enable phpdoc_scalar fixer

.php_cs, classes/Domain/Services/Authentication.php, classes/Infrastructure/Auth/SentryAuthentication.php, tests/Http/Controller/TalkControllerTest.php
This PR
>**phpdoc_no_empty_return** [`@Symfony`]
>
>@return void and @return null annotations should be omitted from phpdocs.
=> Enhancement: Enable phpdoc_no_empty_return fixer

.php_cs, tests/Infrastructure/Auth/SentryIdentityProviderTest.php
This PR
>**no_empty_phpdoc** [`@Symfony`]
>
>There should not be empty PHPDoc blocks.
=> Enhancement: Enable no_empty_phpdoc fixer

Makefile
This PR
💁‍♂️ Enable `xdebug` and run
```
$ make coverage
```
to enjoy a coverage report!
=> Enhancement: Add coverage target

.php_cs, tests/Http/Form/SignupFormTest.php
This PR
>**phpdoc_indent** [`@Symfony`]
>
>Docblocks should have the same indentation as the documented subject.
=> Enhancement: Enable phpdoc_indent fixer

.php_cs, classes/Http/Controller/Admin/ExportsController.php, classes/Http/Controller/PagesController.php
This PR
> **trim_array_spaces** [`@Symfony`]
>
>Arrays should be formatted like function/method arguments, without leading or trailing single line space.
=> Enhancement: Enable trim_array_spaces fixer

classes/Domain/Model/Favorite.php, classes/Domain/Model/TalkComment.php, classes/Http/Controller/Admin/TalksController.php, tests/Http/Controller/Admin/TalksControllerTest.php
This PR updates the admins talk controller to use Illuminate.
It also updates some of the models that have a created field for the created at timestamp, but no updated_at field.
It also adds a few tests for the favorite, select, and rate actions which weren't properly tested yet, and updated other tests for that controller to make proper use of the WebTestCase where possible.
Related to: #506.
=> Refactor: Talks controller to use Illuminate

classes/Domain/Model/Favorite.php, classes/Domain/Model/Talk.php, classes/Domain/Model/User.php, classes/Http/Controller/Admin/SpeakersController.php, classes/Provider/Gateways/WebGatewayProvider.php, factories/Common.php, tests/Domain/Model/TalkTest.php, tests/Domain/Model/UserTest.php, tests/Http/Controller/Admin/SpeakersControllerTest.php, tests/TestResponse.php
This PR changes the speakers controller to use Illuminate.
* It moves the delete functionality out of this controller, and into the models. Overriding the standard delete functionality of the User and Talk model to also delete things related to them.
* It adds options for talk comments and favorites to factory functions.
* It fixes a few routes that still had /admin/ prefixed to them
* It adds assertFlashContains to the TestResponse Class.
The coverage for the SpeakersController is below what i'd like, but ive been running into issues, which i assume are related to the transactions.
The new delete functionality doesn't delete the users comments on other talks, or the entries related to them in the users_groups table. Since this wasn't in the old spot version. Adding this shouldn't be too …
=> Refactor: Speakers controller to use Illuminate

classes/Application/Speakers.php, classes/Domain/Services/IdentityProvider.php, classes/Domain/Speaker/SpeakerProfile.php, classes/Domain/Speaker/SpeakerRepository.php, classes/Domain/Talk/TalkRepository.php, classes/Domain/Talk/TalkSubmission.php, classes/Domain/Talk/TalkWasSubmitted.php, classes/Infrastructure/Auth/SentryIdentityProvider.php, classes/Infrastructure/Persistence/IlluminateSpeakerRepository.php, classes/Infrastructure/Persistence/IlluminateTalkRepository.php, classes/Infrastructure/Persistence/SpotSpeakerRepository.php, classes/Infrastructure/Persistence/SpotTalkRepository.php, classes/Provider/ApplicationServiceProvider.php, tests/Application/SpeakersTest.php, tests/Http/API/TalkApiControllerTest.php, tests/Infrastructure/Persistence/IlluminateSpeakerRepositoryTest.php, tests/Infrastructure/Persistence/IlluminateTalkRepositoryTest.php
This PR adds Illuminate talk and speaker repositories, which replace the spot ones.
It also updates a few other classes that relied on spot specific syntax.
Related to #506.
On another note, this broke one of the API tests, but the API doesn't work at all. It relies on the League\OAuth2\ system, which isn't even required in the composer.json anymore. 
If were still supporting the API i'll fix it up, but it looks like the API hasn't worked in quite some time.
=> Refactor: Change Spot repositories to Illuminate repositories

.travis.yml, classes/Infrastructure/Crypto/PseudoRandomStringGenerator.php, composer.json, composer.lock, migrations/20150519122926_reset_photo_paths.php, tests/Infrastructure/Crypto/PseudoRandomStringGeneratorTest.php
This PR
#526 fails because `random-lib` uses `mcrypt`, which is deprecated in PHP 7.1. This causes the test-suite to fail. For such a use-case as ours, `random_bytes` suffices.
Follows #526.
=> Use `random_bytes` instead of `ircmaxell/random-lib` to get tests passing on PHP 7.1

.php_cs, classes/Http/Form/TalkForm.php
This PR
>**no_alias_functions** [`@Symfony:risky`]
>
>Master functions shall be used instead of aliases.
>
>Risky rule: risky when any of the alias functions are overridden.
=> Enhancement: Enable no_alias_functions fixer

.php_cs, tests/Domain/Entity/Mapper/UserTest.php
This PR
>**no_trailing_comma_in_singleline_array** [`@Symfony`]
>
>PHP single-line arrays should not have trailing comma.
=> Enhancement: Enable no_trailing_comma_in_singleline_array fixer

.travis.yml
❗️ Blocked by #579.
This PR
Follows https://github.com/opencfp/opencfp/pull/561#issuecomment-343460931.
💁‍♂️ Note that we should probably modify in regard to #579, that is, when PHP 7.1 is added to the build matrix. We should probably collect coverage only on the latest stable PHP version we decide to add to the build matrix. 
As you can see below, coverage diffs are now displayed in the build statuses:
=> [WIP] Fix: Always collect coverage

.php_cs, tests/Http/Controller/TalkControllerTest.php
This PR
Replaces #584.
Follows #587.
>**cast_spaces** [`@Symfony`]
>
>A single space or none should be between cast and variable.
>
>
>* `space` (`'none'`, `'single'`): spacing to apply between cast and variable; defaults to `'single'`
=> Enhancement: Enable cast_spaces fixer

.travis.yml, .travis/code-climate.sh
This PR
Follows #581.
💁‍♂️ The idea is to speed up the build by collecting coverage on a single PHP version build only, and using the latest version of it (faster).
=> Enhancement: Collect coverage on a single PHP version only

.codeclimate.yml, PHPMDRuleSet.xml
This PR adds a custom ruleset to our PHP MD code climate check.
Fixes #586.
=> Enhancement: Remove models from static access PHPMD rule

.travis.yml
This PR
Follows #590.
💁‍♂️ See https://travis-ci.org/opencfp/opencfp/jobs/301537620#L755-L756:
```
$ if [[ "$WITH_COVERAGE" == "true" ]]; then code-climate-before-script; fi
code-climate-before-script: command not found
```
=> Fix: Add line dropped earlier

PHPMDRuleSet.xml
It looks like the exceptions need to be fully namespaces.
If this works correctly it should show the issues as being fixed in the Code Climate overview of the PR
=> Fix PHPMD ruleset

tests/TestResponse.php
This PR adds two new test asserts to improve the test suite
The assert target url contains method makes sure it is a redirect response first, since the getTargetUrl method isn't part of the normal response object.
Somewhat related to #599, since this should help improve tests
=> Enhancement: Add new response asserts

classes/Domain/Speaker/SpeakerProfile.php, tests/Domain/Speaker/SpeakerProfileTest.php
This PR updates the speaker profile test to no longer depend on a spot entity, and instead use a model, and the new base test case/ refresh database trait.
Follows #597, #577
=> Update Speaker Profile Test

classes/Application.php, classes/Http/Controller/TalkController.php, classes/Http/View/TalkHelper.php, classes/Provider/TalkHelperProvider.php, classes/Provider/TwigServiceProvider.php, tests/Http/Controller/TalkControllerTest.php
This PR Updates the Talk Controller
Related to #506.
=> Refactor: Talk controller to use Illuminate

.gitignore, CONTRIBUTING.md, Makefile, infection.json.dist
This PR sets up infection testing. Run ```vendor/bin/infection``` to start up the tests or ```make infection```.
These tests take quite some time to run, so i haven't added them to travis. I've added the results of my run for those interested
Follows #599.
858 mutations were generated:
403 mutants were killed
370 mutants were not covered by tests
72 covered mutants were not detected
13 time outs were encountered
Metrics:
Mutation Score Indicator (MSI): 48%
Mutation Code Coverage: 57%
Covered Code MSI: 85%
[infection-log.txt](https://github.com/opencfp/opencfp/files/1470975/infection-log.txt)
=> Enhancement: Set up infection testing

classes/Domain/Model/Talk.php, classes/Domain/Talk/TalkFilter.php, classes/Http/Controller/Admin/TalksController.php, classes/Http/Controller/Reviewer/TalksController.php, classes/Provider/TalkFilterProvider.php, tests/Domain/Model/Interaction/TalkTest.php, tests/Domain/Model/Interaction/UserTest.php, tests/Domain/Model/TalkTest.php, tests/Domain/Model/UserTest.php, tests/Domain/Talk/TalkFilterTest.php, tests/Http/Controller/Reviewer/TalksControllerTest.php
This PR changes the TalkFilter class to use Illuminate. To do so it does the following
Related to #577.
If this and #601 get merged pretty much all of Spot has been removed from usage within the project, except for the API
=> Refactor: Talk Filter 

classes/Provider/ApplicationServiceProvider.php
This PR removes the old dependency reference from the security.random, which
would cause the uploading of profile images to break.
Follows #579 .
=> Fix: remove RandomLib/Factory reference

classes/Domain/Model/Favorite.php, classes/Domain/Model/Talk.php, classes/Domain/Model/TalkComment.php, classes/Domain/Model/TalkMeta.php, classes/Domain/Model/User.php, tests/Domain/Model/TalkMetaTest.php, tests/Domain/Model/UserTest.php
This PR adds the return types to our model relationships, adding a bit more assurance that they are correct (e.g. missing return types).
Follows #610
=> Set return types on model relations

classes/Domain/Speaker/NotAllowedException.php, classes/Domain/Speaker/SpeakerProfile.php, classes/Http/Controller/Reviewer/SpeakersController.php, classes/Http/Controller/Reviewer/TalksController.php, config/development.dist.yml, config/production.dist.yml, resources/views/reviewer/speaker/view.twig, resources/views/reviewer/talks/view.twig, tests/Domain/Speaker/SpeakerProfileTest.php
This PR adds the option to limit what information the reviewers can see about speakers. 
By adding entries to the new config option they can blacklist things the reviewer isn't allowed to see. This would make it possible to open up reviewing to a bigger audience, while keeping private information away from them.
Follows #566 
Related to #485, #415.
=> Feature: Limit speaker information reviewers can see

classes/Application.php, classes/Domain/Model/Talk.php, classes/Domain/Services/TalkFormat.php, classes/Domain/Talk/TalkFormatter.php, classes/Domain/Talk/TalkHandler.php, classes/Domain/Talk/TalkProfile.php, classes/Http/Controller/Admin/TalksController.php, classes/Http/Controller/Reviewer/TalksController.php, classes/Provider/TalkHandlerProvider.php, resources/views/admin/index.twig, resources/views/admin/talks/index.twig, resources/views/admin/talks/view.twig, resources/views/reviewer/index.twig, resources/views/reviewer/talks/index.twig, resources/views/reviewer/talks/view.twig, tests/Domain/Services/TalkFormatterTest.php, tests/Domain/Talk/TalkHandlerTest.php, tests/Domain/Talk/TalkProfileTest.php, tests/Http/Controller/Reviewer/DashboardControllerTest.php
This PR adds the talk profile and talk handler to the project.
The talk profile is the talk version of the speaker profile, and is intended to pass to the views, so those can grab all the data they need from it.
The Talk Handler is responsible for all 'meta' actions on a talk. So it doesn't do deleting/creating etc. But it is responsible for making comments, selecting, favoriting, rating and viewing talks.
I'm pretty sure the names of these objects need improving, so feedback on that, or anything else, is welcome.
=> Refactor: Introduction of the Talk Profile and Talk Handler

classes/Domain/Services/AccountManagement.php, classes/Domain/Services/Authentication.php, classes/Infrastructure/Auth/RoleAccess.php, classes/Infrastructure/Auth/SentryAccountManagement.php, classes/Infrastructure/Auth/SentryAuthentication.php, classes/Infrastructure/Auth/SentryUser.php, classes/Infrastructure/Auth/User.php, classes/Infrastructure/Auth/UserInterface.php, tests/Console/AdminPromoteCommandTest.php, tests/Console/ApplicationTest.php, tests/Http/Controller/Admin/SpeakersControllerTest.php, tests/Http/Controller/DashboardControllerTest.php, tests/Http/Controller/ForgotControllerTest.php, tests/Infrastructure/Auth/RoleAccessTest.php, tests/Infrastructure/Auth/SentryAccountManagementTest.php, tests/Infrastructure/Auth/SentryAuthenticationTest.php, tests/Infrastructure/Auth/SentryUserTest.php, tests/WebTestCase.php
This PR moves the UserInterface up to our own namespace, which allows us to make use of it when moving from sentry to sentinel
Follows #501 .
Related to #498.
=> Refactor: Move the UserInterface up to our own namespace

phpunit.xml.dist
This PR will ignore the API classes for code coverage, and exclude the remaining API tests from the standard testsuite.
This should give a better idea of the code coverage, and speed up the tests just a little bit.
Since phpunit will use ```phpunit.xml``` over ```phpunit.xml.dist``` 
```bash
$ cp phpunit.xml.dist phpunit.xml
```
Should be ran locally to update the file.
=> Enhancement: Update phpunit settings to ignore the API

Makefile
=> Fix: Add infection as phony target

Makefile
=> Fix: Keep targets sorted in Makefile

tests/BaseTestCase.php, tests/WebTestCase.php
=> Fix: Explicitly mark abstract test cases as abstract

tests/BaseTestCase.php, tests/Console/AdminPromoteCommandTest.php, tests/Console/ApplicationTest.php, tests/Domain/Model/AirportTest.php, tests/Domain/Services/PaginationTest.php, tests/Domain/Talk/TalkFilterTest.php, tests/Domain/Talk/TalkHandlerTest.php, tests/Http/Controller/ForgotControllerTest.php, tests/Infrastructure/Auth/SentryAccountManagementTest.php, tests/Infrastructure/Auth/SentryAuthenticationTest.php, tests/Infrastructure/Auth/SentryUserTest.php
This PR
💁‍♂️ This is the visibility as declared on the parent test cases, and there's no need to increase it.
=> Fix: Reduce visibility

PHPMDRuleSet.xml
This PR adds the Environment class to the list of exceptions for the PHPMD static access rule
Somewhat related to #631
=> Enhancement: except Environment from the static access rule

classes/Application/Speakers.php, classes/Domain/Services/ProfileImageProcessor.php, classes/Domain/Speaker/SpeakerProfile.php, classes/Domain/Talk/TalkFilter.php, classes/Http/Controller/BaseController.php
This PR changes a lot of protected variables to private
There were a bunch of protected variables that had no reason to be protected. 
The public variables in the ```BaseController``` are now protected, since there is no need for outside classes to call those.
=> Enhancement: Reduce visibility

tests/EnvironmentTest.php
=> Fix: Cover equals()

classes/Environment.php
=> Fix: No need to invoke method

.php_cs, classes/Domain/Model/Talk.php, classes/Http/View/TalkHelper.php, tests/Console/AdminPromoteCommandTest.php, tests/Console/ApplicationTest.php, tests/Http/Controller/Admin/SpeakersControllerTest.php, tests/Http/Controller/DashboardControllerTest.php, tests/Http/Controller/ForgotControllerTest.php, tests/Http/Controller/ProfileControllerTest.php, tests/Http/Controller/SignupControllerTest.php, tests/Http/Controller/TalkControllerTest.php, tests/Infrastructure/Auth/SentryAccountManagementTest.php, tests/Infrastructure/Auth/SentryAuthenticationTest.php
This PR
>**phpdoc_no_package** [`@Symfony`]
>
>`@package` and `@subpackage` annotations should be omitted from phpdocs.
=> Enhancement: Enable phpdoc_no_package fixer

.php_cs, classes/Console/BaseCommand.php, classes/Domain/Model/User.php, classes/Domain/Services/ProfileImageProcessor.php, classes/Http/Controller/Admin/ExportsController.php, classes/Http/Controller/Admin/SpeakersController.php, tests/Helper/DataBaseInteraction.php, tests/Helper/RefreshDatabase.php, tests/Http/Controller/Admin/SpeakersControllerTest.php, tests/Http/Controller/Admin/TalksControllerTest.php, tests/Http/Controller/ProfileControllerTest.php, tests/Http/Controller/Reviewer/SpeakerControllerTest.php, tests/Http/Controller/Reviewer/TalksControllerTest.php, tests/Http/Controller/TalkControllerTest.php, web/index.php, web/index_dev.php
This PR
>**concat_space** [`@Symfony`]
>
>Concatenation should be spaced according configuration.
>
>
>* `spacing` (`'none'`, `'one'`): spacing to apply around concatenation operator; defaults to `'none'`
=> Enhancement: Enable and configure concat_space fixer

.php_cs, classes/Application/Speakers.php, classes/Domain/Model/Airport.php, classes/Domain/Model/User.php, classes/Domain/Services/Authentication.php, classes/Domain/Services/IdentityProvider.php, classes/Domain/Services/ProfileImageProcessor.php, classes/Http/API/TalkController.php, classes/Infrastructure/Auth/OAuthIdentityProvider.php, classes/Infrastructure/Auth/SentryAuthentication.php, classes/Infrastructure/Auth/SentryIdentityProvider.php
This PR
>**phpdoc_order**
>
>Annotations in phpdocs should be ordered so that param annotations come first, then throws annotations, then return annotations.
=> Enhancement: Enable phpdoc_order fixer

.php_cs, classes/Domain/Model/Talk.php, classes/Domain/Services/TalkRating/TalkRatingStrategy.php, classes/Http/Form/Form.php
This PR
>**phpdoc_trim** [`@Symfony`]
>
>Phpdocs should start and end with content, excluding the very first and last line of the docblocks.
=> Enhancement: Enable phpdoc_trim fixer

classes/Domain/Speaker/SpeakerProfile.php, resources/views/admin/index.twig, resources/views/admin/talks/index.twig, resources/views/admin/talks/view.twig, resources/views/reviewer/index.twig, resources/views/reviewer/talks/index.twig, resources/views/reviewer/talks/view.twig, tests/Integration/Domain/Speaker/SpeakerProfileTest.php
This PR
I think this used to be a feature but it probably got lost during #518
=> Enhancement: Link to speaker page from talks

tests/Unit/Application/SpeakersTest.php, tests/Unit/Console/AdminPromoteCommandTest.php, tests/Unit/Console/ApplicationTest.php, tests/Unit/ContainerAwareTest.php, tests/Unit/Domain/CallForProposalTest.php, tests/Unit/Domain/Services/ResetEmailerTest.php, tests/Unit/Domain/Services/TalkRating/YesNoRatingTest.php, tests/Unit/Domain/Talk/TalkFilterTest.php, tests/Unit/Domain/Talk/TalkSubmissionTest.php, tests/Unit/Faker/GeneratorTest.php, tests/Unit/Http/API/ApiControllerTest.php, tests/Unit/Http/API/ProfileApiControllerTest.php, tests/Unit/Http/API/TalkApiControllerTest.php, tests/Unit/Http/Controller/FlashableTraitTest.php, tests/Unit/Http/Form/SignupFormTest.php, tests/Unit/Http/Form/TalkFormTest.php, tests/Unit/Infrastructure/Auth/RoleAccessTest.php, tests/Unit/Infrastructure/Auth/SentryIdentityProviderTest.php, tests/Unit/Infrastructure/Auth/SpeakerAccessTest.php, tests/Unit/Infrastructure/Crypto/PseudoRandomStringGeneratorTest.php, tests/Unit/Provider/SymfonySentrySessionTest.php
❗️ Blocked by #651.
This PR
Follows #641.
=> Fix: Replace coversNothing with appropriate covers annotations

tests/BaseTestCase.php, tests/Unit/Application/SpeakersTest.php, tests/Unit/Console/AdminPromoteCommandTest.php, tests/Unit/Console/ApplicationTest.php, tests/Unit/Domain/Services/ResetEmailerTest.php
=> Enhancement: Use MockeryPHPUnitIntegration trait

tests/Unit/Domain/Services/PaginationTest.php, tests/Unit/Domain/Talk/TalkFilterTest.php
This PR
Follows https://github.com/opencfp/opencfp/pull/629#issuecomment-346014095.
💁‍♂️ Next up, moving `BaseTestCase` into the `OpenCFP\Test\Integration` namespace.
=> Fix: Do not extend BaseTestCase if unit test

tests/Unit/Console/Command/AdminPromoteCommandTest.php
=> Fix: Move test into appropriate namespace

classes/Application.php
=> Refactor the global error handler

Makefile
=> Fix: Remove duplicates from the makefile

.php_cs, tests/Integration/Infrastructure/Persistence/IlluminateSpeakerRepositoryTest.php, tests/Unit/ContainerAwareTest.php, tests/Unit/Domain/Services/ResetEmailerTest.php, tests/Unit/Http/Controller/FlashableTraitTest.php, tests/Unit/Infrastructure/Auth/SentryIdentityProviderTest.php, tests/Unit/Provider/SymfonySentrySessionTest.php
This PR
>**no_multiline_whitespace_before_semicolons**
>
>Multi-line whitespace before closing semicolon are prohibited.
=> Enhancement: Enable no_multiline_whitespace_before_semicolon fixer

tests/Unit/Domain/Services/AuthenticationExceptionTest.php
=> Fix: Add test for AuthenticationException

tests/Unit/EnvironmentTest.php
=> Enhancement: Use data provider for testing against different environment types

classes/Environment.php, tests/Unit/EnvironmentTest.php, web/index.php
This PR
Follows https://github.com/opencfp/opencfp/pull/671#discussion_r152666225.
=> Enhancement: Allow to pass in $_SERVER

.php_cs, classes/Application.php, classes/Domain/Model/User.php, classes/Http/Form/Form.php, classes/Http/Form/SignupForm.php, tests/Unit/ContainerAwareTest.php, tests/Unit/Infrastructure/Auth/SentryIdentityProviderTest.php
This PR
>**phpdoc_types_order**
>
>Sorts PHPDoc types.
>
>
>* `null_adjustment` (`'always_first'`, `'always_last'`, `'none'`): forces the position of null (overrides `sort_algorithm`); defaults to `'always_first'`
>* `sort_algorithm` (`'alpha'`, `'none'`): the sorting algorithm to apply; defaults to `'alpha'`
=> Enhancement: Enable phpdoc_types_order fixer

classes/Http/Form/SignupForm.php
=> Fix: True is not a type

tests/Integration/Infrastructure/Auth/SentryUserTest.php, tests/Unit/Domain/Services/ResetEmailerTest.php
=> Fix: Use more appropriate assertions

tests/BaseTestCase.php, tests/Helper/DataBaseInteraction.php, tests/Integration/Http/Controller/DashboardControllerTest.php, tests/Integration/Http/Controller/ForgotControllerTest.php, tests/TestResponse.php, tests/Unit/Application/SpeakersTest.php, tests/Unit/Console/ApplicationTest.php, tests/Unit/Console/Command/AdminPromoteCommandTest.php, tests/Unit/ContainerAwareTest.php, tests/Unit/Domain/CallForProposalTest.php, tests/Unit/Domain/Talk/TalkSubmissionTest.php, tests/Unit/Http/API/ApiControllerTest.php, tests/Unit/Http/API/ProfileApiControllerTest.php, tests/Unit/Http/API/TalkApiControllerTest.php, tests/Unit/Http/Controller/FlashableTraitTest.php, tests/Unit/Infrastructure/Auth/SentryIdentityProviderTest.php, tests/Unit/Provider/SymfonySentrySessionTest.php
=> Fix: Use return type declarations

tests/Integration/Http/Controller/PagesControllerTest.php
=> Fix: Use constant

.php_cs, tests/TestResponse.php
This PR
>**is_null** [`@Symfony:risky`]
>
>Replaces is_null(parameter) expression with `null === parameter`.
>
>Risky rule: risky when the function ``is_null()`` is overridden.
>
>
>* `use_yoda_style` (`bool`): whether Yoda style conditions should be used; defaults to `true`
=> Enhancement: Enable and configure is_null fixer

tests/Unit/Domain/ValidationExceptionTest.php
=> Fix: Cover named constructor

.php_cs, factories/Common.php
This PR
>**no_blank_lines_after_phpdoc** [`@Symfony`]
>
>There should not be blank lines between docblock and the documented element.
=> Enhancement: Enable no_blank_lines_after_phpdoc fixer

.php_cs, web/index_dev.php
This PR
>**function_to_constant** [`@Symfony:risky`]
>
>Replace core functions calls returning constants with the constants.
>
>Risky rule: risky when any of the configured functions to replace are overridden.
>
>
>* `functions` (`array`): list of function names to fix; defaults to `['get_class', 'php_sapi_name', 'phpversion', 'pi']`
=> Enhancement: Enable function_to_constant fixer

.php_cs, classes/Domain/Model/Talk.php, classes/Http/Controller/Reviewer/SpeakersController.php
This PR
>**ternary_operator_spaces** [`@Symfony`]
>
>Standardize spaces around ternary operator.
=> Enhancement: Enable ternary_operator_spaces fixer

.php_cs, tests/TestResponse.php
This PR
>**function_typehint_space** [`@Symfony`]
>
>Add missing space between function's argument and its typehint.
=> Enhancement: Enable function_typehint_space fixer

.php_cs, classes/Application.php, classes/Console/BaseCommand.php, classes/Domain/CallForProposal.php, classes/Domain/Model/User.php, classes/Domain/Speaker/SpeakerProfile.php, classes/Environment.php, classes/Http/Controller/ForgotController.php, classes/Http/Controller/ProfileController.php, classes/Http/Controller/SignupController.php, classes/Http/Controller/TalkController.php, classes/Infrastructure/Auth/SentryAuthentication.php, tests/Integration/Domain/Speaker/SpeakerProfileTest.php, tests/helpers.php
This PR
>**unary_operator_spaces** [`@Symfony`]
>
>Unary operators should be placed adjacent to their operands.
=> Enhancement: Enable unary_operator_spaces fixer

.php_cs, classes/Infrastructure/OAuth/AccessTokenStorage.php, classes/Infrastructure/OAuth/AuthCodeStorage.php, classes/Infrastructure/OAuth/ClientStorage.php, classes/Infrastructure/OAuth/RefreshTokenStorage.php, classes/Infrastructure/OAuth/SessionStorage.php
This PR
>**no_useless_return**
>
>There should not be an empty return statement at the end of a function.
=> Enhancement: Enable no_useless_return fixer

.php_cs, classes/Http/Controller/ProfileController.php
This PR
>**no_singleline_whitespace_before_semicolons** [`@Symfony`]
>
>Single-line whitespace before closing semicolon are prohibited.
=> Enhancement: Enable no_singleline_whitespace_before_semicolons fixer

tests/Unit/Http/API/TalkApiControllerTest.php
=> Fix faulty coversNothing

Makefile
This PR
Somewhat related to https://github.com/opencfp/opencfp/pull/705#discussion_r153040895.
=> Enhancement: Add asset target to Makefile

config/development.dist.yml, config/production.dist.yml, config/testing.yml, resources/views/home.twig, resources/views/layouts/splash.twig
=> Make the path for background configurable

.php_cs.dist, classes/Application.php, classes/Application/Speakers.php, classes/Console/Application.php, classes/Domain/Services/TalkRating/TalkRatingContext.php, classes/Http/OAuth/AuthorizationController.php, classes/Infrastructure/Persistence/IlluminateSpeakerRepository.php, classes/Provider/ApplicationServiceProvider.php, classes/Provider/Gateways/OAuthGatewayProvider.php, classes/Provider/SentryServiceProvider.php, classes/Provider/TwigServiceProvider.php, tests/Helper/SentryTestHelpers.php, tests/Integration/Domain/Model/AirportTest.php, tests/Integration/Domain/Services/TalkFormatterTest.php, tests/Unit/Console/ApplicationTest.php, tests/Unit/Console/Command/AdminPromoteCommandTest.php
This PR
>**new_with_braces** [`@Symfony`]
>
>All instances created with new keyword must be followed by braces.
=> Enhancement: Enable new_with_braces fixer

.php_cs.dist, classes/Infrastructure/Auth/SentryAuthentication.php
This PR
>**no_blank_lines_after_class_opening** [`@Symfony`]
>
>There should be no empty lines after class opening brace.
=> Enhancement: Enable no_blank_lines_after_class_opening fixer

.php_cs.dist, tests/helpers.php
This PR
>**no_superfluous_elseif**
>
>Replaces superfluous `elseif` with `if`.
=> Enhancement: Enable no_superfluous_elseif fixer

classes/ContainerAware.php
This PR
Somewhat related to #618.
💁‍♂️ In order to be able to properly test components currently using it, they should stop using it and have their dependencies injected. Marking the trait as `@deprecated` is a first step into that direction.
=> Fix: Mark ContainerAware trait as deprecated

bin/opencfp, classes/Console/Application.php, classes/Console/Command/UserCreateCommand.php, tests/Unit/Console/ApplicationTest.php, tests/Unit/Console/Command/UserCreateCommandTest.php
This PR
Somewhat related to #714.
Somewhat related to #618.
=> Enhancement: Decouple UserCreateCommand from application container

.php_cs.dist, classes/Http/Controller/Admin/ExportsController.php, tests/Integration/Domain/Speaker/SpeakerProfileTest.php, tests/Unit/Domain/Services/PaginationTest.php, tests/Unit/Domain/Services/TalkRating/YesNoRatingTest.php
This PR
>**whitespace_after_comma_in_array** [`@Symfony`]
>
>In array declaration, there MUST be a whitespace after each comma.
=> Enhancement: Enable whitespace_after_comma_in_array fixer

.php_cs.dist, classes/Domain/Services/TalkRating/YesNoRating.php, classes/Domain/Talk/TalkHandler.php, classes/Http/Controller/Admin/ExportsController.php, classes/Http/Form/Form.php, classes/Http/Form/SignupForm.php, classes/Http/Form/TalkForm.php
This PR
>**no_unneeded_control_parentheses** [`@Symfony`]
>
>Removes unneeded parentheses around control statements.
>
>
>* `statements` (`array`): list of control statements to fix; defaults to `['break', 'clone', 'continue', 'echo_print', 'return', 'switch_case', 'yield']`
=> Enhancement: Enable no_unneeded_control_parentheses fixer

classes/Http/Controller/TalkController.php
This PR
The bug was introduced in https://github.com/opencfp/opencfp/commit/b0563ebef6acbac6a0ccb90750390a5a376c290b (by me)
=> Bugfix: Allow talks to be deleted again

classes/Http/Controller/Admin/SpeakersController.php, classes/Http/Controller/TalkController.php, resources/views/admin/speaker/index.twig, resources/views/dashboard.twig, resources/views/forms/_talk.twig, resources/views/layouts/default.twig, tests/Integration/Http/Controller/Admin/SpeakersControllerTest.php, tests/Integration/Http/Controller/TalkControllerTest.php
This PR
A helpful security audit from @enygma revealed a few spots where our forms and some GET actions with side effects were not protected using CSRF tokens. This PR fixes those spots and also adds CSRF protection to talk creation.
=> CSRF additions

classes/Http/Controller/Admin/TalksController.php, classes/Http/Controller/Reviewer/TalksController.php, tests/Integration/Http/Controller/Admin/TalksControllerTest.php, tests/Integration/Http/Controller/Reviewer/TalksControllerTest.php
This PR
Casting a string like 'blabla' to an int will make it 0 in php. Which isn't really what we want here.
=> Fix: Check ratings a bit more strict

composer.json, composer.lock
The dependency was added in the great silex 2.0 merge, yet i can't find
any place that it is actually implemented
This PR
As far as i could find it wasn't used anywhere.
```git grep coveralls``` didn't give any results besides the ```composer.json``` & ```composer.lock```.
=> Remove coveralls dev dependency

.php_cs.dist, classes/Http/Controller/BaseController.php
This PR
>**combine_consecutive_unsets**
>
>Calling `unset` on multiple items should be done in one call.
=> Enhancement: Enable combine_consecutive_unsets fixer

.php_cs.dist, classes/Environment.php
This PR
>**self_accessor** [`@Symfony`]
>
>Inside a classy element "self" should be preferred to the class name itself.
=> Enhancement: Enable self_accessor fixer

.php_cs.dist, classes/ContainerAware.php
This PR
>**phpdoc_no_alias_tag** [`@Symfony`]
>
>No alias PHPDoc tags should be used.
>
>
>* `replacements` (`array`): mapping between replaced annotations with new ones; defaults to `['property-read' => 'property', 'property-write' => 'property', 'type' => 'var', 'link' => 'see']`
=> Enhancement: Enable phpdoc_no_alias_tag fixer

classes/Console/Command/UserCreateCommand.php, tests/Unit/Console/Command/UserCreateCommandTest.php
=> Fix: Catch appropriate exception

.php_cs.dist, classes/Domain/CallForProposal.php, classes/Domain/Model/Talk.php, classes/Domain/Speaker/SpeakerProfile.php, classes/Domain/Speaker/SpeakerRepository.php, classes/Domain/Talk/TalkSubmission.php, classes/Infrastructure/Persistence/IlluminateSpeakerRepository.php
This PR
>**phpdoc_annotation_without_dot** [`@Symfony`]
>
>Phpdocs annotation descriptions should not be a sentence.
=> Enhancement: Enable phpdoc_annotation_without_dot fixer

classes/Domain/Speaker/SpeakerRepository.php, classes/Infrastructure/Persistence/IlluminateSpeakerRepository.php
=> Fix: Add return type declaration

classes/Domain/Talk/TalkSubmission.php
=> Fix: Use || instead of in conditions

classes/Domain/Speaker/SpeakerRepository.php, classes/Domain/Talk/TalkRepository.php, classes/Infrastructure/Persistence/IlluminateSpeakerRepository.php, classes/Infrastructure/Persistence/IlluminateTalkRepository.php, tests/Integration/Infrastructure/Persistence/IlluminateSpeakerRepositoryTest.php
This PR
Follows https://github.com/opencfp/opencfp/pull/744#discussion_r153315056.
=> Fix: Do not return boolean from persist()

classes/Http/Controller/Reviewer/DashboardController.php, tests/Integration/Http/Controller/Reviewer/DashboardControllerTest.php
This PR
Some deployment environments would error because they couldn't find the class as described in the web gateway provider.
This also fixes the reviewers dashboard controller test which was checking the admin controller instead.
=> Fix: capitalization error

classes/Application.php
=> Fix: Path should be a string

tests/BaseTestCase.php, tests/Integration/Http/Controller/ForgotControllerTest.php, tests/Integration/phpunit.xml.dist, tests/Unit/ApplicationTest.php, tests/Unit/Console/ApplicationTest.php, tests/Unit/Console/Command/AdminPromoteCommandTest.php, tests/Unit/Provider/SentinelServiceProviderTest.php, tests/Unit/phpunit.xml.dist
This PR
💁‍♂️ Currently cannot run a single unit tests from within PhpStorm without configuring the working directory. Also, PhpStorm doesn't provide support for constants declared within `phpunit.xml`, so this is much more helpful.
=> Fix: Remove dependency on BASE_PATH constant

classes/Domain/Speaker/SpeakerProfile.php
=> Fix: Remove unnecessary ternary

PHPMDRuleSet.xml
This PR
So far every instance of this rule being broken is logical, so this makes more sense than adding every single exception/model to a list.
Somewhat related to #763 
I'm making sure this actually does what i expect it to before assigning a reviewer.
=> Update PHPMD rule set

bin/opencfp, classes/Console/Application.php, classes/Console/Command/ReviewerPromoteCommand.php, tests/Unit/Console/ApplicationTest.php, tests/Unit/Console/Command/ReviewerPromoteCommandTest.php, tests/Unit/phpunit.xml.dist
This PR
Follows #717.
Related to #714.
💁‍♂️ For reference, see:
* http://symfony.com/blog/new-in-symfony-3-2-console-improvements-part-2
* https://github.com/symfony/console/blob/a5a80c40bb9d67f9a992fac8ba3a542fa09e47c8/Tests/TerminalTest.php#L19-L32
=> Enhancement: Decouple ReviewerPromoteCommand from application container

classes/Http/Controller/SecurityController.php, resources/views/security/login.twig
This PR
💁‍♂️ This has the advantage that a) I don't need to type in my email again if a login failed, and b) that I can see whatever the email address is I typed in earlier.
=> Enhancement: Render email in login form

classes/Domain/Speaker/SpeakerProfile.php
=> Fix: Add return type declarations

classes/Console/Command/ReviewerPromoteCommand.php, tests/Unit/Console/Command/ReviewerPromoteCommandTest.php
This PR
Follows #624.
Follows #722.
💁‍♂️ My bad, I should have updated these in #722.
=> Fix: References to Sentry in ReviewerPromoteCommand

classes/Infrastructure/Auth/SentinelAccountManagement.php, classes/Infrastructure/Auth/UserNotFoundException.php, tests/Unit/Infrastructure/Auth/UserNotFoundExceptionTest.php
=> Enhancement: Extract dedicated constructors

.php_cs.dist
This PR
Related to https://github.com/opencfp/opencfp/pull/771#discussion_r153736272.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/v2.8.3#usage:
>**no_multiline_whitespace_around_double_arrow** [`@Symfony`]
>
>Operator `=>` should not be surrounded by multi-line whitespaces.
=> Enhancement: Enable no_multiline_whitespace_around_double_arrow fixer

classes/Domain/Speaker/SpeakerProfile.php, tests/Unit/Domain/Speaker/SpeakerProfileTest.php
This PR
Without the toArray it would return a collection, and throw a fatal error.
Follows #760
=> Fix return type of speaker profile

bin/opencfp, classes/Console/Application.php, classes/Console/Command/ReviewerDemoteCommand.php, tests/Unit/Console/ApplicationTest.php, tests/Unit/Console/Command/ReviewerDemoteCommandTest.php
=> Enhancement: Decouple ReviewerDemoteCommand from application container

tests/Integration/Http/Controller/Reviewer/SpeakersControllerTest.php
This PR
💁‍♂️ The system under test is the [`SpeakersController`](https://github.com/opencfp/opencfp/blob/b607dc45cb0c58edaec1605d4ef61e18207cd44c/classes/Http/Controller/Reviewer/SpeakersController.php).
=> Fix: Name of test class

classes/Domain/Speaker/SpeakerProfile.php, tests/Unit/Domain/Speaker/SpeakerProfileTest.php
=> Fix: Hotel is actually a boolean

.php_cs.dist, migrations/0_schema.php, migrations/20140823091041_favorites.php, migrations/20140828144530_add_id_to_speaker_table.php, migrations/20140828145029_add_hotel_and_transportation_cost_fields.php, migrations/20140902174929_remove_speaker_table.php, migrations/20141121173412_add_talk_meta.php, migrations/20141122213222_create_talk_comment.php, migrations/20141201172522_alter_user_column_defaults.php, migrations/20141203111136_alter_talk_column_defaults.php, migrations/20150518024706_create_league_oauth_tables.php, migrations/20150519122926_reset_photo_paths.php, migrations/20150702132854_fix_defaults_for_users_table.php, migrations/20151012165609_alter_talk_columns_allow_null.php, migrations/20151214140200_airports.php, migrations/20160106061843_fix_zero_dates.php, migrations/20161224211743_talks_tags_migration.php, migrations/20171019025925_add_needs_profile_flag.php, migrations/20171107125309_reviewer_role_migration.php, migrations/20171120102354_sentinel_migration.php, migrations/20171120112704_activate_user_migration.php, migrations/20171120122725_roles_migration.php, migrations/20171120123411_user_roles_migration.php, migrations/20171128134740_remove_useless_items_migration.php
This PR
💁‍♂️ I can't think of a reason why the same rules should not apply to migrations.
=> Enhancement: Do not exclude migrations from php-cs-fixer

migrations/20171129142655_use_non_nullable_boolean.php
This PR
Follows #779.
Follows https://github.com/opencfp/opencfp/pull/758#discussion_r153525414.
=> Fix: Use non-nullable TINYINT for boolean fields

classes/Application.php, classes/Application/Speakers.php, classes/Domain/CallForPapers.php, classes/Http/Controller/DashboardController.php, classes/Http/Controller/SignupController.php, classes/Http/Controller/TalkController.php, classes/Provider/ApplicationServiceProvider.php, classes/Provider/CallForPapersProvider.php, classes/Provider/Gateways/WebGatewayProvider.php, tests/Integration/Http/Controller/TalkControllerTest.php, tests/Unit/Application/SpeakersTest.php, tests/Unit/Domain/CallForPapersTest.php, tests/WebTestCase.php
This PR
💁‍♂️ Running
```
$ git grep -i callforproposal
```
after this change yields nothing now.
=> Fix: Rename CallForProposals to CallForPapers

classes/Domain/Services/AccountManagement.php, classes/Infrastructure/Auth/SentinelAccountManagement.php, tests/Unit/Infrastructure/Auth/SentinelAccountManagementTest.php
This PR
💁‍♂️ `Admin` doesn't really seem like a default value that makes sense.
=> Fix: Remove default value

classes/Application.php
=> Fix: Extract template map from switch statement

config/development.dist.yml, config/production.dist.yml, config/testing.yml
This PR
Follows #694, #754, #578.
=> Remove API toggle from configuration files

bin/opencfp, classes/Console/Application.php, classes/Console/Command/AdminPromoteCommand.php, tests/Unit/Console/ApplicationTest.php, tests/Unit/Console/Command/AdminPromoteCommandTest.php
=> Enhancement: Decouple AdminPromoteCommand from application container

bin/opencfp, classes/Console/Application.php, classes/Console/Command/AdminDemoteCommand.php, tests/Unit/Console/ApplicationTest.php, tests/Unit/Console/Command/AdminDemoteCommandTest.php
=> Enhancement: Decouple AdminDemoteCommand from application container

classes/Application/Speakers.php, classes/Provider/ApplicationServiceProvider.php, tests/Unit/Application/SpeakersTest.php
=> Fix: Remove unused dependency

classes/Http/Controller/SecurityController.php, classes/Http/Controller/SignupController.php
This PR
There was no real reason why it had to be passed to the function directly
=> Remove application object from function call

classes/Http/Controller/Admin/SpeakersController.php, resources/views/admin/speaker/index.twig, resources/views/admin/speaker/view.twig
=> Fix: Display the airport information the speaker entered

.php_cs.dist, tests/Integration/Domain/Model/AirportTest.php, tests/Integration/Domain/Model/TalkTest.php, tests/Integration/Domain/Services/TalkFormatterTest.php, tests/Integration/Domain/Talk/TalkHandlerTest.php, tests/Integration/Infrastructure/Auth/SentinelAccountManagementTest.php, tests/Integration/Infrastructure/Auth/SentinelAuthenticationTest.php, tests/Unit/Application/SpeakersTest.php, tests/Unit/Console/ApplicationTest.php, tests/Unit/Domain/Services/TalkRating/TalkRatingTest.php, tests/Unit/Domain/Talk/TalkFilterTest.php, tests/Unit/Domain/Talk/TalkProfileTest.php, tests/Unit/Domain/Talk/TalkSubmissionTest.php, tests/Unit/EnvironmentTest.php, tests/Unit/Http/Form/SignupFormTest.php, tests/Unit/Http/Form/TalkFormTest.php, tests/Unit/Infrastructure/Auth/SentinelAccountManagementTest.php, tests/Unit/Infrastructure/Crypto/PseudoRandomStringGeneratorTest.php
This PR
Follows #766 
:tipping_hand_man: For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/v2.8.3#usage:
>* **php_unit_strict**
>
>  PHPUnit methods like ``assertSame`` should be used instead of
``assertEquals``.
>
>  *Risky rule: risky when any of the functions are overridden.*
>
>  Configuration options:
>
>  - ``assertions`` (``array``): list of assertion methods to fix; defaults to
``['assertAttributeEquals', 'assertAttributeNotEquals', 'assertEquals',
'assertNotEquals']``
=> Enhancement: Enable php_unit_strict fixer

classes/Console/Command/AdminDemoteCommand.php, classes/Console/Command/AdminPromoteCommand.php, classes/Console/Command/ReviewerDemoteCommand.php, classes/Console/Command/ReviewerPromoteCommand.php, tests/Unit/Console/Command/AdminDemoteCommandTest.php, tests/Unit/Console/Command/AdminPromoteCommandTest.php, tests/Unit/Console/Command/ReviewerDemoteCommandTest.php, tests/Unit/Console/Command/ReviewerPromoteCommandTest.php
=> Fix: Extract variable for role name

.github/CONTRIBUTING.md, README.md
=> Fix: Move CONTRIBUTING.md into .github

classes/Application.php
=> Fixed spelling mistake

classes/Domain/Services/UserAccess.php, classes/Infrastructure/Auth/RoleAccess.php, classes/Infrastructure/Auth/SpeakerAccess.php
=> Fix: Use type declaration

classes/Infrastructure/Auth/SentinelAccountManagement.php, tests/Integration/Infrastructure/Auth/SentinelAccountManagementTest.php, tests/Unit/Infrastructure/Auth/SentinelAccountManagementTest.php
This PR
Follows https://github.com/opencfp/opencfp/pull/809#discussion_r154369159.
=> Fix: Do not return anything from activate()

composer.json, composer.lock, tests/Unit/Infrastructure/Auth/SentinelAuthenticationTest.php
=> Fix: Use tag when requiring mockery/mockery

classes/Domain/Services/UserAccess.php, classes/Infrastructure/Auth/RoleAccess.php, classes/Infrastructure/Auth/SpeakerAccess.php, classes/Provider/Gateways/WebGatewayProvider.php, tests/Unit/Infrastructure/Auth/RoleAccessTest.php, tests/Unit/Infrastructure/Auth/SpeakerAccessTest.php
This PR
There really is no reason to pass it the entire application object, when all it needs is the Authentication object.
A future PR idea would be to rename this to something like ``RoleValidator``` and have it implement a validator interface. That way the naming would make more sense
=> Fix: UserAccess to use Auth object

classes/Domain/Services/Authentication.php, classes/Http/Controller/SignupController.php, classes/Infrastructure/Auth/RoleAccess.php, classes/Infrastructure/Auth/SentinelAuthentication.php, classes/Infrastructure/Auth/SpeakerAccess.php, classes/Provider/Gateways/WebGatewayProvider.php, tests/Integration/Http/Controller/DashboardControllerTest.php, tests/Integration/Infrastructure/Auth/SentinelAuthenticationTest.php, tests/Unit/Infrastructure/Auth/RoleAccessTest.php, tests/Unit/Infrastructure/Auth/SentinelAuthenticationTest.php, tests/Unit/Infrastructure/Auth/SpeakerAccessTest.php, tests/WebTestCase.php
This PR
💁‍♂️ I believe something like `isAuthenticated()` or `isSignedIn()` or `isLoggedIn()` reveals the intent better than something as generic as `check()`. It also aligns nicely with the [`Authentication::authenticate()`](https://github.com/opencfp/opencfp/blob/d872d646e9b561e9cb8ed41fc3e1a4abdbaddfeb/classes/Domain/Services/Authentication.php#L20-L28).
=> Fix: Rename method

tests/Helper/Faker/GeneratorTrait.php, tests/Unit/Faker/GeneratorTest.php
This PR
💁‍♂️ This prevents needlessly importing the `GeneratorTrait` multiple times along an inheritance chain.
=> Fix: Mark getFaker() as final

classes/Console/Command/UserDemoteCommand.php, classes/Console/Command/UserPromoteCommand.php, tests/Unit/Console/Command/UserDemoteCommandTest.php, tests/Unit/Console/Command/UserPromoteCommandTest.php
This PR
Follows #819.
💁‍♂️ Next step, after merging #818: handling of `RoleNotFoundException`.
=> Fix: Simplify promotion and demotion

tests/BaseTestCase.php, tests/Integration/Http/Controller/DashboardControllerTest.php, tests/Unit/Infrastructure/Auth/SentinelIdentityProviderTest.php
=> Fix: Pull up import of GeneratorTrait

classes/Domain/Services/AccountManagement.php, classes/Infrastructure/Auth/RoleNotFoundException.php, classes/Infrastructure/Auth/SentinelAccountManagement.php, tests/Unit/Infrastructure/Auth/RoleNotFoundExceptionTest.php, tests/Unit/Infrastructure/Auth/SentinelAccountManagementTest.php
=> Enhancement: Throw RoleNotFoundException if role was not found

tests/Unit/Console/Command/UserDemoteCommandTest.php, tests/Unit/Console/Command/UserPromoteCommandTest.php
This PR
💁‍♂️ This brings them more in line with those added in #838 and #839.
=> Fix: Rename test methods

classes/Console/Command/UserDemoteCommand.php, classes/Console/Command/UserPromoteCommand.php, tests/Unit/Console/Command/UserDemoteCommandTest.php, tests/Unit/Console/Command/UserPromoteCommandTest.php
=> Enhancement: Catch RoleNotFoundException

bin/opencfp, classes/Console/Command/ClearCacheCommand.php
This PR
Follows #792.
Found this when trying to run the internal php server on master.
=> Fix cache clear command

classes/Console/Command/UserDemoteCommand.php, classes/Console/Command/UserPromoteCommand.php, tests/Unit/Console/Command/UserDemoteCommandTest.php, tests/Unit/Console/Command/UserPromoteCommandTest.php
This PR
Follows https://github.com/opencfp/opencfp/pull/824#issuecomment-348823711.
=> Enhancement: Catch generic exception

tests/Unit/Console/Command/UserDemoteCommandTest.php, tests/Unit/Console/Command/UserPromoteCommandTest.php
This PR
Follows #841.
🤦‍♂️ Sorry!
=> Fix: Use faker() instead of unavailable getFaker()

resources/views/home.twig, resources/views/layouts/splash.twig
This PR
💁‍♂️ This mostly affects larger displays, but I think it wasn't intended to look as it does.
=> Fix: Set background-size to cover

bin/opencfp, classes/Http/Controller/Admin/DashboardController.php, classes/Http/Controller/Admin/ExportsController.php, classes/Http/Controller/Admin/SpeakersController.php, classes/Http/Controller/Admin/TalksController.php, classes/Http/Controller/BaseController.php, classes/Http/Controller/ForgotController.php, classes/Http/Controller/ProfileController.php, classes/Http/Controller/Reviewer/DashboardController.php, classes/Http/Controller/Reviewer/SpeakersController.php, classes/Http/Controller/Reviewer/TalksController.php, classes/Http/Controller/SecurityController.php, classes/Http/Controller/SignupController.php, classes/Http/Controller/TalkController.php
This PR
💁‍♂️ Introducing temporary variables for services fetched from the application container allows to annotate them with the type to which they resolve, and thus increases visibility - making it easier to see which services are actually used, as well as navigating the code.
=> Fix: Increase visibility of services shared by container

.php_cs.dist
=> Fix: Exclude cached php files from php cs fixer

script/server
This PR
I'm not 100% sure why, but since upgrading to PHP 7.1.12 i had an issue with the internal php server, for some reason it was looking for the server.php in the web folder, rather then the root of the project. 
So this add a check to see if the user is on php 7.1.12, and if so, it points it to the correct place
=> Fix php internal server

tests/Unit/ProjectCodeTest.php
=> Enhancement: Assert that production classes have unit tests

classes/Http/Controller/Admin/ExportsController.php, classes/Provider/Gateways/WebGatewayProvider.php
The `ExportsController` is being constructed via DI.
Follows #855.
=> Removed ContainerAware from ExportsController

classes/Http/Controller/TalkController.php, classes/Provider/Gateways/WebGatewayProvider.php, tests/Integration/Http/Controller/TalkControllerTest.php
The ProfileController is being constructed via DI.
This is a rather large controller with a lot of dependencies that are not used by all actions. It should definitely be split up in a later PR.
Follows #855.
=> Removed ContainerAware from TalkController

classes/Application.php, classes/Infrastructure/Event/ExceptionListener.php, tests/Unit/Infrastructure/Event/ExceptionListenerTest.php
Preparation for #618: Middlewares are a Silex-only feature. Under the hood they're implemented as event listeners. So if we want them to survive the framework switch, we need to turn them into event subscribers.
This PR does this for the error middleware.
After the switch, this subscriber can probably be replaced with the exception listener that is provided by TwigBundle.
=> Converted error middleware into an event subscriber

tests/Unit/Infrastructure/Event/ExceptionListenerTest.php
=> Fix: Add @covers annotation to EventListenerTest

tests/Integration/Http/Controller/Admin/TalksControllerTest.php, tests/Integration/Http/Controller/Reviewer/TalksControllerTest.php
This PR
Related to https://github.com/opencfp/opencfp/pull/852#issuecomment-349336156.
💁‍♂️ Probably best reviewed with https://github.com/opencfp/opencfp/pull/853/files?diff=split.
=> Fix: Use data provider

classes/Infrastructure/Event/AuthenticationListener.php, classes/Provider/Gateways/WebGatewayProvider.php, tests/TestResponse.php, tests/Unit/Infrastructure/Event/AuthenticationListenerTest.php
Preparation for #618: All middlewares that check for an authenticated user have been replaced by a single event subscriber that can be reused in Symfony.
=> Converted authentication middleware into an event subscriber

classes/Infrastructure/Event/TwigGlobalsListener.php, classes/Infrastructure/Templating/TwigExtension.php, classes/Provider/Gateways/WebGatewayProvider.php, classes/Provider/TwigServiceProvider.php, tests/Unit/Infrastructure/Event/Fixtures/global_with_admin.txt, tests/Unit/Infrastructure/Event/Fixtures/global_with_anonymous_user.txt, tests/Unit/Infrastructure/Event/Fixtures/global_with_reviewer.txt, tests/Unit/Infrastructure/Event/Fixtures/globals.txt.twig, tests/Unit/Infrastructure/Event/TwigGlobalsListenerTest.php, tests/Unit/Infrastructure/Templating/Fixtures/functions.txt, tests/Unit/Infrastructure/Templating/Fixtures/functions.txt.twig, tests/Unit/Infrastructure/Templating/TwigExtensionTest.php
Preparation for #618:
* The middleware that sets global Twig variables based on the current request has been refactored to an event subscriber.
* All custom Twig functions have been bundled in a single Twig extension.
* Some tests have been added to cover that functionality.
It should be possible to reuse both classes when switching to Symfony.
=> Refactored twig middleware into an event subscriber and a twig extension

classes/Console/Application.php, tests/Unit/Console/ApplicationTest.php
The console application still depends on the Silex container although the commands don't depend on it anymore.
=> Removed unused container dependency from the console application.

classes/Http/Controller/Admin/TalksController.php, classes/Http/Controller/Reviewer/TalksController.php
This PR
Follows https://github.com/opencfp/opencfp/pull/852#issuecomment-349339120.
=> Fix: Explicitly return Response objects

tests/BaseTestCase.php, tests/Helper/DataBaseInteraction.php, tests/Integration/Http/Controller/Admin/SpeakersControllerTest.php, tests/Integration/Http/Controller/ForgotControllerTest.php, tests/Integration/Http/Controller/TalkControllerTest.php, tests/Integration/Infrastructure/Auth/SentinelUserTest.php, tests/Integration/MigrationsTest.php, tests/TestResponse.php, tests/WebTestCase.php
This PR decouples most tests from the Pimple container by making them access services through the PSR-11 interface. This way, it should not matter to them whether the container is Pimple or Symfony DI.
TODO in a follow-up: The service swapping is going to be interesting with a compiled container. 😱
=> Decoupled direct container access in tests via PSR-11

classes/Http/Controller/Reviewer/TalksController.php
This PR
Follows #874.
Blocks #852.
=> Fix: Do not return string

tests/Integration/Http/Controller/Admin/TalksControllerTest.php, tests/Integration/Http/Controller/Reviewer/TalksControllerTest.php
This PR
Follows #853.
Follows https://github.com/opencfp/opencfp/pull/852#issuecomment-349339120.
=> Fix: Use more specific assertions for responses

classes/Http/Controller/Admin/DashboardController.php, classes/Http/Controller/Admin/ExportsController.php, classes/Http/Controller/Admin/SpeakersController.php, classes/Http/Controller/Admin/TalksController.php, classes/Http/Controller/DashboardController.php, classes/Http/Controller/ForgotController.php, classes/Http/Controller/PagesController.php, classes/Http/Controller/ProfileController.php, classes/Http/Controller/Reviewer/DashboardController.php, classes/Http/Controller/Reviewer/SpeakersController.php, classes/Http/Controller/Reviewer/TalksController.php, classes/Http/Controller/SecurityController.php, classes/Http/Controller/SignupController.php, classes/Http/Controller/TalkController.php, tests/Unit/ProjectCodeTest.php
This PR
Somewhat related to #850.
💁‍♂️ There are a few controller actions that actually also return `false`, not sure what's kicking in there later to actually return a response.
=> Fix: Add return type declarations to controller actions

classes/Provider/Gateways/WebGatewayProvider.php
While analyzing the routing, I've found some routes that point to controller actions that do not exist (anymore?). I think, we can remove them.
=> Removed orphaned routes.

classes/Application.php, classes/Provider/TwigServiceProvider.php
=> Fix: normalize twig provider

classes/Http/Controller/SecurityController.php
This PR
This caused a fatal error when trying to log in with wrong credentials
=> Fix: Remove app reference in security controller

classes/Http/Controller/PagesController.php
This PR
Only the home page uses the number_of_talks variable, so there was no need to pass it to the other templates.
=> Remove unused variable being passed to twig template

classes/Domain/Services/ResetEmailer.php, classes/Provider/ResetEmailerServiceProvider.php, tests/Unit/Domain/Services/ResetEmailerTest.php
This PR makes `ResetEmailer` use the Twig environment directly instead of depending on a template object. This will make it easier to wire that class as a service.
This make the class aware of the actual template it needs to use, but I don't see this as a big problem.
=> Make ResetEmailer depend on Twig instead of a Twig template

classes/Infrastructure/Event/CsrfValidationListener.php, classes/Provider/Gateways/WebGatewayProvider.php, tests/Unit/ProjectCodeTest.php
CSRF tokens are being checked in an event subscriber now.
This one is a bit tricky. Since Symfony does not offer the possibility to attach listeners to routes, I'm marking the affected routes with a request attribute.
As a auggestion: You should consider using Symfony forms because would gain CSRF protection out of the box.
=> Turned CSRF checker into an event subscriber

bin/opencfp, classes/Application.php, classes/Console/Command/ClearCacheCommand.php, classes/Provider/Gateways/ConsoleGatewayProvider.php, tests/Unit/Console/Command/ClearCacheCommandTest.php, tests/Unit/ProjectCodeTest.php
This PR moves the construction of the console application to the DI container. It also decouples the cache clear command from the `Path` object which simplifies some test cases.
=> Construct the console application via DI

classes/Application.php, classes/Infrastructure/Event/DatabaseSetupListener.php, classes/Provider/ApplicationServiceProvider.php, tests/Unit/ProjectCodeTest.php
The setup logic for Eloquent was moved out of the application class.
=> Moved Eloquent setup into a very early event listener

tests/Unit/Provider/SentinelServiceProviderTest.php
I missed that one when refactoring the test cases to use PSR-11.
Follows #876.
=> Sentinel test should use the container from BaseTestCase.

classes/Application.php, classes/Provider/TestingServiceProvider.php, tests/BaseTestCase.php, tests/Helper/MockableAuthenticator.php, tests/Integration/Http/Controller/DashboardControllerTest.php, tests/Integration/WebTestCase.php, tests/Unit/ProjectCodeTest.php
Swapping services is really not fun with the Symfony container. With this PR, I tried to get around swapping services for authentication. WDYT?
=> Use a mockable authenticator instead of service swapping

classes/Infrastructure/Event/TwigGlobalsListener.php
This PR
Due to this having a priority of 512, the same as the ```DatabaseSetupListener``` ,it would fire before the db connection was set up and would throw a fatal error.
=> Reduce twig priority

classes/Http/Controller/DashboardController.php, classes/Http/Controller/PagesController.php, classes/Provider/Gateways/WebGatewayProvider.php, tests/Integration/Http/Controller/PagesControllerTest.php, tests/Unit/ProjectCodeTest.php
=> Fix: Suffix controller actions with Action

tests/Helper/ResponseHelper.php
=> Fix: Assertion failure messages

classes/Application.php, classes/Http/Controller/Admin/SpeakersController.php, classes/Http/Controller/ProfileController.php, classes/Http/Controller/Reviewer/SpeakersController.php, classes/Infrastructure/Templating/TwigExtension.php, classes/Path.php, classes/PathInterface.php, classes/Provider/Gateways/WebGatewayProvider.php, classes/Provider/ImageProcessorProvider.php, classes/Provider/TwigServiceProvider.php, resources/views/admin/speaker/index.twig, resources/views/admin/speaker/view.twig, resources/views/admin/talks/view.twig, resources/views/reviewer/speaker/index.twig, resources/views/reviewer/speaker/view.twig, resources/views/reviewer/talks/view.twig, tests/Integration/Infrastructure/Templating/TwigExtensionTest.php, tests/Unit/PathTest.php
This PR
Related to #894.
This is a first step to making the uploading of profile pictures a bit more manageable on production environments where we can't, or don't want to, write to our own file system. If this gets merged, the only thing that needs to be changed in order to use another storage is the reference in the Path functions.
=> Enhancement: remove hardcoded references to uploads folder

.php_cs.dist, classes/Domain/Model/Airport.php, classes/Domain/Talk/TalkFilter.php, tests/Integration/Domain/Talk/TalkHandlerTest.php, tests/Integration/Http/Controller/Admin/ExportsControllerTest.php, tests/Integration/Infrastructure/Auth/SentinelAuthenticationTest.php
This PR
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/v2.9.0#usage:
>**class_attributes_separation** [`@Symfony`]
>
>Class, trait and interface elements must be separated with one blank line.
>
>
>* `elements` (`array`): list of classy elements; `'const'`, `'method'`, `'property'`; defaults to `['const', 'method', 'property']`
=> Enhancement: Enable and configure class_attributes_separation fixer

tests/Integration/Http/Controller/Admin/SpeakersControllerTest.php, tests/Integration/Http/Controller/TalkControllerTest.php, tests/Integration/WebTestCase.php
This PR eliminates more service swapping on the container by using actual CSRF tokens in integration tests instead of mocking the CSRF validator.
=> Don't swap the CSRF token validator

tests/Unit/Http/Action/Page/HomePageActionTest.php, tests/Unit/Http/Action/Page/SpeakerPackageActionTest.php, tests/Unit/Http/Action/Page/TalkIdeasActionTest.php
=> Fix: Assert identity

tests/Unit/Http/Action/DashboardActionTest.php
=> Fix: Adjust covers annotation

classes/Http/Form/ForgotForm.php, resources/views/security/forgot_password.twig
This PR adds validation to the reset form and makes sure that flash messages are displayed on that form.
Unfortunately, `ResetControllerTest` does not catch either of those issues because the form validation is mocked and the flash bag is accessed directly. I'm currently checking how to improve tests like that one.
=> Render flash message on reset form and validate the form.

classes/Infrastructure/Event/TwigGlobalsListener.php, composer.json, composer.lock, tests/BaseTestCase.php, tests/Integration/Http/Controller/ForgotControllerTest.php, tests/Integration/Infrastructure/Event/ExceptionListenerTest.php, tests/Integration/WebTestCase.php
This PR integrates Silex' test client into the integration test suite. This allows us to emulate user interaction better and with less mocking.
The PR also contains a better `ResetControllerTest` that covers the issue fixed by PR #933.
Follows #933.
=> Use Silex' test client for integration tests

tests/Integration/Provider/SentinelServiceProviderTest.php, tests/Unit/ProjectCodeTest.php
This PR
Blocks #936.
/cc @derrabus
=> Fix: Move integration test into appropriate namespace

tests/Helper/DataBaseInteraction.php, tests/Helper/RefreshDatabase.php
This PR
Related to #936.
💁‍♂️ This is useful to prevent multiple imports, as well as tests attempting to override these methods.
=> Fix: Mark methods as final to prevent multiple imports

tests/Helper/ResponseHelper.php
=> Fix: Assert that flash is not null

tests/Integration/Http/Controller/Admin/SpeakersControllerTest.php, tests/Integration/Http/Controller/ForgotControllerTest.php
This PR removes swapping of the `AccountManagement` service. Instead, the real service is used with data that has been written to the database.
Follows #934.
=> Use the database instead of mocking AccountManagement

tests/Unit/Infrastructure/Auth/SentinelIdentityProviderTest.php
This PR
Blocks #936.
/cc @derrabus
=> Fix: Extend from PHPUnit\Framework\TestCase

classes/Domain/CallForPapers.php, tests/Integration/Http/Controller/TalkControllerTest.php, tests/Integration/WebTestCase.php
This PR uses reflection calls in integration tests to modify the `CallForPapers` service instead of swapping the whole service with a mocked one.
=> Don't swap the CallForPapers service

classes/Provider/TestingServiceProvider.php, tests/Helper/MockableIdentityProvider.php, tests/Integration/Http/Action/DashboardActionTest.php, tests/Integration/Http/Action/Talk/ViewActionTest.php, tests/Integration/WebTestCase.php
This PR removes all swapping of the `application.speakers` service.
=> Don't swap the speakers service

classes/Infrastructure/Auth/SymfonySentinelSession.php, classes/Provider/SentinelServiceProvider.php, tests/Unit/Infrastructure/Auth/SymfonySentinelSessionTest.php
This PR moves the class `SymfonySentinelSession` out of the provider namespace as it is not really a service provider. Plus, when switching to Symfony, that class would be the only one left in that namespace.
=> Moved SymfonySentinelSession out of the Provider namespace

classes/Provider/SwiftMailerServiceProvider.php, tests/Integration/Http/Controller/TalkControllerTest.php
This PR disables email delivery in testing environment. This way, we don't need to mock SwiftMailer just to make it stop sending mails.
Follows #902.
=> When in testing environment, don't deliver any mails

composer.json, composer.lock
This PR removes the Symfony Security component from the dependencies as it is obviously not used by OpenCFP.
=> Remove unused Symfony Security component.

classes/Domain/Services/TalkFormat.php, classes/Domain/Talk/TalkFormatter.php, tests/Integration/Domain/Services/TalkFormatterTest.php
This PR
Related to #908.
💁‍♂️ Running
```
$ git grep -i createdFormattedOutput
```
yields no results other than in tests, the interface, and the single implementation.
=> Fix: Remove unused method

tests/Integration/Http/Controller/ForgotControllerTest.php, tests/Integration/WebTestCase.php
This PR removes the remaining calls to the `WebTestCase::swap()` method. That means that our integration tests do not modify the container anymore, which is very helpful for the Symfony migration.
Unfortunately, I had to kill one test case for this. I don't see a good way to simulate inside an integration test that the reset email could not be sent. It would probably be better to cover this with unit tests.
Follows #618.
Prepares #895.
=> Removed remaining calls to WebTestCase::swap()

README.md, classes/Provider/HtmlPurifierServiceProvider.php, classes/Provider/TwigServiceProvider.php, config/development.dist.yml, config/production.dist.yml, config/testing.yml
This PR removes the switch to disable the cache. Once we switch to Symfony, we don't have a choice but to maintain a cache directory, because Symfony operates on a compiled container and router and therefore requires a cache.
Preparation for #895.
=> Removed switch to disable the cache

classes/Domain/Talk/TalkProfile.php, tests/Unit/Domain/Talk/TalkProfileTest.php
This PR
Blocks #895.
/cc @derrabus
=> Fix: Properly set up test doubles

tests/Integration/Http/Controller/Admin/DashboardControllerTest.php, tests/Integration/Http/Controller/Admin/ExportsControllerTest.php, tests/Integration/Http/Controller/Admin/SpeakersControllerTest.php, tests/Integration/Http/Controller/Reviewer/DashboardControllerTest.php, tests/Integration/Http/Controller/SignupControllerTest.php, tests/Integration/Http/Controller/TalkControllerTest.php, tests/Integration/WebTestCase.php
=> Fix: Extract method that fetches session from container

tests/Unit/Http/Form/SignupFormTest.php
This PR
💁‍♂️ There are other places where `stdClass` is used to mock something different, but it appears to be a lot of work to fix these tests. Maybe someone else is interested in fixing them?
Running
```
$ git grep stdClass
```
yields
```
tests/Unit/Application/SpeakersTest.php:154:    private function getSpeakerWithNoTalks(): \stdClass
tests/Unit/Application/SpeakersTest.php:157:        $stub = m::mock(\stdClass::class);
tests/Unit/Application/SpeakersTest.php:164:    private function getSpeakerFromMisbehavingRelation(): \stdClass
tests/Unit/Application/SpeakersTest.php:167:        $stub     = m::mock(\stdClass::class);
tests/Unit/Application/SpeakersTest.php:171:        $talk = m::mock(\stdClass::class);
tests/Unit/Application/SpeakersTest.php:184:    private function …
```
=> Fix: Do not use stdClass to mock something different

classes/Infrastructure/Auth/CsrfValidator.php, tests/Unit/Infrastructure/Auth/CsrfValidatorTest.php
This PR replaces `CsrfTokenManager` with `CsrfTokenManagerInterface`in type-hints.
=> Type-hint for the interface instead of the implementation.

classes/Provider/Gateways/ConsoleGatewayProvider.php
=> Fix: No need to wrap single argument

web/index.php
This PR adds Symfony's debug error handler to the development environment.
This is another small piece that I managed to cut out of #895. If something goes wrong during the application bootstrap (I simulated this by writing garbage into my development.yml), the error handler renders a nice error page with a stack trace.
**Before**
**After**
Note that exceptions that happen _during_ request processing are still caught and handled by your `ExceptionListener`.
=> Register a debug error handler for development

tests/Unit/Http/Action/Talk/DeleteActionTest.php
=> Fix: Extend from AbstractActionTestCase

phinx.yml.dist
This PR adds quote to a YAML string starting with a `%` character. This establishes forward compatibility with the stricter parsing rules in Symfony YAML 4.0.
Reference: https://github.com/symfony/symfony/blob/4.0/src/Symfony/Component/Yaml/CHANGELOG.md#400
=> Quote strings starting with percent character in YAML files.

composer.json, composer.lock, tests/Unit/Infrastructure/Auth/SentinelIdentityProviderTest.php
This PR upgrades the `aptoma/twig-markdown` library to 2.0. The currently used version of that library accesses deprecated Twig functionality.
=> Upgrade aptoma/twig-markdown to 2.0

tests/Unit/Infrastructure/Auth/SentinelIdentityProviderTest.php
This PR
Somewhat related to #973.
🤷‍♂️ Maybe it helps. For reference, also see https://travis-ci.org/opencfp/opencfp/jobs/317783176#L874-L878.
=> Fix: Use PHPUnit mocking facilities

classes/Http/Controller/TalkController.php, resources/config/routing.yml
The merge of #925 went a bit wrong: The old action method is still there and the routing still points to it. This PR fixes this.
Follows #925.
=> Removed the already replaced editAction from TalkController

classes/Kernel.php, composer.json, composer.lock, resources/config/config_development.yml, resources/config/routing_development.yml
This PR enables the Symfony developer toolbar and the profiler in development environment. It the application runs in production environment, the profiler remains inaccessible.
~~The PR includes #895 in its full glory, please only look at the last commit of the branch.~~
Screenshots:
=> Add Symfony Profiler to development environment

classes/Http/Action/DashboardAction.php, classes/Http/Action/Page/HomePageAction.php, classes/Http/Action/Page/SpeakerPackageAction.php, classes/Http/Action/Page/TalkIdeasAction.php, classes/Http/Action/Talk/EditAction.php, classes/Http/Action/Talk/ViewAction.php, classes/Kernel.php, composer.json, composer.lock, tests/Unit/Http/Action/AbstractActionTestCase.php, tests/Unit/Http/Action/DashboardActionTest.php, tests/Unit/Http/Action/Page/HomePageActionTest.php, tests/Unit/Http/Action/Page/SpeakerPackageActionTest.php, tests/Unit/Http/Action/Page/TalkIdeasActionTest.php, tests/Unit/Http/Action/Talk/EditActionTest.php, tests/Unit/Http/Action/Talk/ViewActionTest.php
This PR enables SensioFrameworkExtraBundle which allows us to configure controllers with annotations. It also adds `@Template` annotations to actions that render templates. This allows us to return an array with template variables instead of a `Response` object, so we do not need to interface with Twig directly anymore.
~~The PR includes #895 in its full glory, please only look at the last commit of the branch.~~
=> Use template annotation on actions

phpunit.xml.dist
=> Enhancement: Configure memory limit in phpunit.xml.dist

tests/Unit/Http/Action/AbstractActionTestCase.php
See: https://travis-ci.org/opencfp/opencfp/builds/318070759
`createTwigMock` doesn't exist and tests fail. This PR adds `createTwigMock` to `AbstractActionTestCase`.
This is my bad as I didn't realize the rebase from https://github.com/opencfp/opencfp/pull/955 was broken.
=> Fix broken build from forgotten mock factory

.php_cs.dist, classes/Console/Command/UserPromoteCommand.php, classes/Http/Controller/Admin/ExportsController.php, classes/Http/Controller/ForgotController.php, classes/Http/View/TalkHelper.php, classes/Infrastructure/Auth/SentinelAuthentication.php, migrations/20140828144530_add_id_to_speaker_table.php, migrations/20140828145029_add_hotel_and_transportation_cost_fields.php, tests/Integration/Http/Controller/Admin/TalksControllerTest.php, tests/Unit/Domain/Services/AuthenticationExceptionTest.php, tests/Unit/Domain/Speaker/SpeakerProfileTest.php, tests/Unit/EnvironmentTest.php, tests/Unit/Infrastructure/Auth/SentinelAccountManagementTest.php
This PR
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/v2.9.0#usage:
>**no_whitespace_in_blank_line** [`@Symfony`]
>
>Remove trailing whitespace at the end of blank lines.
=> Enhancement: Enable no_whitespace_in_blank_line fixer

.github/CONTRIBUTING.md
=> CONTRIBUTING update

tests/Unit/Console/Command/UserCreateCommandTest.php, tests/Unit/Console/Command/UserDemoteCommandTest.php, tests/Unit/Console/Command/UserPromoteCommandTest.php, tests/Unit/Domain/Speaker/SpeakerProfileTest.php, tests/Unit/Http/Action/AbstractActionTestCase.php, tests/Unit/Http/Action/DashboardActionTest.php, tests/Unit/Http/Action/Signup/IndexActionTest.php, tests/Unit/Http/Action/Talk/CreateActionTest.php, tests/Unit/Http/Action/Talk/DeleteActionTest.php, tests/Unit/Http/Action/Talk/EditActionTest.php, tests/Unit/Http/Action/Talk/ViewActionTest.php, tests/Unit/Infrastructure/Auth/SentinelIdentityProviderTest.php, tests/Unit/Infrastructure/CacheWarmer/HtmlPurifierWarmerTest.php, tests/Unit/Infrastructure/Repository/IlluminateUserRepositoryTest.php
This PR
Follows #985.
Related to #983.
💁‍♂️ Marking these methods as `@deprecated` emphasises` that - going forward - we don't want to use the internal mocking facilities of `phpunit/phpunit` anymore.
=> Fix: Mark methods creating mocks as deprecated

.php_cs.dist, tests/Unit/Http/Action/Talk/EditActionTest.php
This PR
Follows #958.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/v2.9.0#usage:
>**general_phpdoc_annotation_remove**
>
>Configured annotations should be omitted from phpdocs.
>
>
>* `annotations` (`array`): list of annotations to remove, e.g. `["author"]`; defaults to `[]`
=> Enhancement: Enable and configure general_phpdoc_annotation_remove fixer

classes/Http/Action/Forgot/IndexAction.php, classes/Http/Controller/ForgotController.php, classes/Http/Form/FormFactory.php, resources/config/routing.yml, resources/config/services/services.yml, tests/Integration/Http/Action/Forgot/IndexActionTest.php, tests/Integration/Http/Controller/ForgotControllerTest.php, tests/Unit/Http/Action/Forgot/IndexActionTest.php, tests/Unit/Http/Form/FormFactoryTest.php
=> Enhancement: Extract IndexAction from ForgotController

classes/Http/Controller/SecurityController.php, resources/config/routing.yml, resources/views/security/login.twig, tests/Integration/Http/Action/Security/IndexActionTest.php
=> Enhancement: Use TemplateController to render login

Makefile
=> Fix: Dont copy phinx.yml if it is not needed

.php_cs.dist
This PR
Follows #917.
💁‍♂️ I believe explicitly disabling the fixer, rather than just removing it, sends the signal that a) we are aware of the fixer, and b) have decided not to use it (anymore).
=> Fix: Explicitly disable php_unit_test_class_requires_covers fixer

tests/Integration/Domain/Model/Interaction/TalkTest.php, tests/Integration/Domain/Model/Interaction/UserTest.php, tests/Integration/Http/Action/Admin/DashboardActionTest.php, tests/Integration/Http/Action/Admin/Talk/IndexActionTest.php, tests/Integration/Http/Action/Reviewer/DashboardActionTest.php, tests/Integration/Http/Action/Reviewer/Talk/IndexActionTest.php, tests/Integration/Http/Action/Talk/CreateActionTest.php, tests/Integration/Http/Controller/ForgotControllerTest.php, tests/Integration/Infrastructure/Auth/SentinelAccountManagementTest.php, tests/Integration/Infrastructure/Auth/SentinelAuthenticationTest.php, tests/Integration/TransactionalTestCase.php, tests/Integration/WebTestCase.php
This PR
Follows https://github.com/opencfp/opencfp/pull/991#issuecomment-352565555.
```
$ make integration
vendor/bin/phpunit --testsuite integration
PHPUnit 6.5.4 by Sebastian Bergmann and contributors.
Runtime:       PHP 7.0.25
Configuration: /Users/am/Sites/opencfp/opencfp/phpunit.xml.dist
.................................................................................................................................................................                                                                                                                                             161 / 161 (100%)
Time: 42.77 seconds, Memory: 354.00MB
OK (161 tests, 935 assertions)
```
```
$ make integration
vendor/bin/phpunit --testsuite integration
PHPUnit 6.5.4 by Sebastian Bergmann and …
```
=> Enhancement: Wrap tests in transactions

tests/Helper/RefreshDatabase.php
This PR
Related to https://github.com/opencfp/opencfp/issues/721.
💁‍♂️ I believe we are better of if we have a single means of resetting the database to a known state, and that should involve fetching the database connection from the container, rather than manually creating it.
=> Fix: Mark RefreshDatabase trait as deprecated

tests/Integration/Domain/Model/AirportTest.php
=> Fix: Only use RefreshDatabase when needed

tests/Integration/Http/Action/Admin/Talk/ViewActionTest.php, tests/Integration/Http/Action/Talk/UpdateActionTest.php
This PR
Follows #959.
Follows #1001.
Follows #1004.
Blocks #996.
Blocks #1002.
Blocks #1003.
💁‍♂️ This should fix the broken build.
=> Fix: Use TransactionalTestCase instead of removed RequiresDatabaseReset

classes/Http/Controller/Reviewer/TalksController.php
=> Fix: Use appropriate route when redirecting

classes/Http/Form/Form.php
This PR
💁‍♂️ We should probably use Symfony forms instead.
=> Fix: Deprecate abstract Form class

Makefile
This PR
Run ```make coverage type=html``` to build the phpunit coverage report
It currently goes to the coverage folder, this was already in the gitignore, so it seemed like a logical place
=> Add html coverage to makefile

resources/views/home.twig, resources/views/user/edit.twig
This PR resolves this 🌶 
We recently added an include for the flash template before content on all templates extending `default.twig`. There were a few forgotten usages of flash that caused issues like this. I `grep`-ed for occurrences of `_flash.twig` and removed what made sense.\
Follows #900.
=> Since adding flash before default content, we do not need doubles

Makefile
This PR
Before this we tried to set up the database without a proper `testing.yml` file being present, and thus it would error.
=> Fix: set up test config file before running database

Makefile
=> Fix: Add test-env to phony targets

tests/Integration/WebTestCase.php
=> Fix: Reduce visibility and mark as final

tests/Integration/WebTestCase.php
This PR
Blocks #1030.
💁‍♂️ I have been scratching my head because tests in #1030 are failing. Then it dawned on me that of course, when we have integration tests run from a test class that uses the `RefreshDatabase` trait, and the next test class does not use the `RefreshDatabase` trait, but instead implements the `TransactionalTestCase`, then the database won't be fresh in the latter, and tests might fail (as they currently do in #1030). So unfortunately, until we remove the `RefreshDatabase` trait (working on it), we'll have to refresh the database twice.
=> Fix: Refresh database before and after class

phpunit.xml.dist
This PR
Blocks #1030.
💁‍♂️ Running tests fails there because the current memory limit of `512M` is exceeded a bit.
=> Fix: Increase memory limit

classes/Http/Form/TalkForm.php, tests/Unit/Http/Form/TalkFormTest.php
This PR
* Before you would only see the first thing that caused an error, now you get to see all the errors in your form submission.
=> Fix talk form validation

tests/Integration/Http/Controller/Reviewer/TalksControllerTest.php
This PR
Follows #924.
🤷‍♂️ Should have removed these tests in #924. Also see [`ViewActionTest`](https://github.com/opencfp/opencfp/blob/6102f17445eabb9287f1807976dde7c3897db5d7/tests/Integration/Http/Action/Reviewer/Talk/ViewActionTest.php).
=> Fix: Remove duplicated tests

tests/Unit/ProjectCodeTest.php
This PR
Follows #1021.
Follows #1041.
💁‍♂️ Forgot to remove them here.
=> Fix: Remove references to undefined classes

.travis.yml
=> Fix: No need to install SQLite on Travis

classes/Http/Action/Admin/Speaker/PromoteAction.php, tests/Integration/Http/Action/Admin/Speaker/PromoteActionTest.php, tests/Unit/Http/Action/Admin/Speaker/PromoteActionTest.php
This PR
Follows https://github.com/opencfp/opencfp/pull/1048#discussion_r158587123.
=> Fix: Split try-and-catch block

resources/config/config_testing.yml, tests/Integration/Http/Action/Admin/Speaker/PromoteActionTest.php, tests/Integration/Http/Action/Talk/CreateProcessActionTest.php, tests/Integration/Http/Action/Talk/DeleteActionTest.php, tests/Integration/Http/Action/Talk/EditActionTest.php, tests/Integration/Http/Action/Talk/UpdateActionTest.php, tests/Integration/Http/Controller/Admin/SpeakersControllerTest.php, tests/Integration/Infrastructure/Event/AuthenticationListenerTest.php
This PR removes Silex-compatible service aliases.
In order to keep the diff of #895 low, I had added two service aliases, so I didn't have to adjust too many test cases when switching between Silex and Symfony. Now that Silex is gone for good, we can safely remove those aliases and use the Symfony service IDs in those tests.
Follows #895.
=> Removed Silex-compatible service aliases

composer.json, composer.lock
This PR upgrades Phinx to 0.9.2. The main difference for us is that the new release is compatible with Symfony 4.
=> Upgraded Phinx to 0.9.2

classes/Kernel.php
This PR moves the registration of `WebServerBundle` to the development environment section.
It should be possible to run the application in production environment with only production dependencies. This is currently not the case because the kernel tries to register the `WebServerBundle` which is a dev dependency.
Since you probably don't want to run the production system on php's built-in webserver, the bundle is now only available in the development environment.
Follows #992.
=> Load WebServerBundle in development only

classes/Kernel.php, resources/config/config.yml, resources/views/dashboard.twig, resources/views/home.twig, resources/views/layouts/default.twig, resources/views/layouts/splash.twig, resources/views/security/signup.twig
This PR removes our global `app` template variable.
The reason for this change is that Symfony uses that variable to provide access to certain objects like the environment, the current request or whether the application runs in debug mode. If we override it like we currently do, we cannot make use of that functionality.
Reference: https://symfony.com/doc/3.4/templating/app_variable.html
Furthermore, the information that is currently being queried from that variables is already redundantly present in another global variable, `site`. Our `app` contains more information than `site`, but I could not find a twig line where information from `app` is accessed that `site` doesn't also contain. So, from my point of view, if safe to redirect all access to the `site` variable and drop `app`.
=> Don't override the global app template variable

Makefile
This PR
Due to the new printer infection was not working correctly, this PR forces phpunit to use the default printer for infection
Follows #1040.
=> Fix: make infection 

Makefile
This PR
Unit tests shouldn't interact with the cache, so no need to clear it before those, since it is quite slow to run these commands.
This should make sure we don't run our tests against an old cache
=> Enhancement: Make cache

classes/Http/Action/Signup/ProcessAction.php
This PR removes the unused dependency on `Twig_Environment` from the `OpenCFP\Http\Action\Signup\ProcessAction` class.
=> Removed unused Twig dependency

classes/Kernel.php, tests/Helper/DependencyInjection/TestingPass.php, tests/Unit/ProjectCodeTest.php
=> Enhancement: Move TestingPass to Test namespace

classes/Http/Action/Admin/Talk/RateAction.php, classes/Http/Action/Reviewer/Talk/RateAction.php, classes/Http/Action/Signup/ProcessAction.php, classes/Infrastructure/Validation/RequestValidator.php, resources/config/services/infrastructure.yml, tests/Unit/Infrastructure/Validation/RequestValidatorTest.php
This PR extracts the `validate()` method, that has been copied into three action classes, into a separate class that is loaded as a service.
Follows: #1045, #1043, #1022
Relates to: #1023
=> Moved request validation into a service

tests/Integration/Http/Action/Admin/DashboardActionTest.php, tests/Integration/Http/Action/Admin/Talk/IndexActionTest.php, tests/Integration/Http/Action/Admin/Talk/ViewActionTest.php, tests/Integration/Http/Action/Reviewer/DashboardActionTest.php, tests/Integration/Http/Action/Reviewer/Speaker/ViewActionTest.php, tests/Integration/Http/Action/Reviewer/Talk/IndexActionTest.php, tests/Integration/Http/Action/Reviewer/Talk/ViewActionTest.php, tests/Integration/Http/Action/Signup/IndexActionTest.php, tests/Integration/Http/Action/Talk/CreateActionTest.php, tests/Integration/Http/Action/Talk/CreateProcessActionTest.php, tests/Integration/Http/Action/Talk/EditActionTest.php, tests/Integration/Http/Action/Talk/UpdateActionTest.php, tests/Integration/Infrastructure/Event/AuthenticationListenerTest.php, tests/Integration/WebTestCase.php
=> Fix: Don't assume a user identifier

composer.json
This PR
💁‍♂️ Running
```
$ composer validate
```
yields
```
./composer.json is valid for simple usage with composer but has
strict errors that make it unable to be published as a package:
See https://getcomposer.org/doc/04-schema.md for details on the schema
description : The property description is required
require.ezyang/htmlpurifier : unbound version constraints (dev-master) should be avoided
```
=> Fix: Add missing description to composer.json

script/test
The script/test file refers to the old phinx.yml instead of phinx.php configuration file.
This PR
* Replaces the old phinx configuration filename extension `.yml` with `.php` in `script/test`.
Fixes #1080
=> Fix phinx configuration filename in script/test

classes/Console/Command/UserCreateCommand.php, tests/Unit/Console/Command/UserCreateCommandTest.php
* "-e" shortcut is already used by the global --env option
This PR
* changes the shortcut for the `--email` option of `user:create` from "-e" to "-m".
Fixes #1078
=> Fix duplicate usage of command option shortcut "-e"

classes/Http/Controller/BaseController.php
This PR 
Its a left over from refactoring controllers into actions
=> Remove redirectBack

resources/views/dashboard.twig
This PR
Hardly related to #1083.
=> Fix: Remove @ from Twitter link and title

resources/assets/sass/app.scss
=> Make sure login is not too thin on mobile

Makefile
=> Fix: Unknown target

.travis.yml, composer.json, composer.lock
This PR
For reference, see http://php.net/supported-versions.php:
=> Fix: Drop support for PHP 7.0

.travis.yml, composer.json, composer.lock
This PR
💁‍♂️ For reference, see 
* https://github.com/localheinz/composer-normalize
* https://localheinz.com/blog/2018/01/15/normalizing-composer.json/
=> Enhancement: Normalize composer.json

composer.lock
This PR updates the following vendor packages:
* Symfony Components (v3.4.4 => v3.4.6)
* symfony/polyfill-* (v1.6.0 => v1.7.0)
* twig/twig (v2.4.4 => v2.4.6)
* sensio/framework-extra-bundle (v5.1.3 => v5.1.6)
* symfony/monolog-bundle (v3.1.2 => v3.2.0)
* symfony/swiftmailer-bundle (v3.1.6 => v3.2.1)
* psr/simple-cache (1.0.0 => 1.0.1)
=> Symfony 3.4.6 and related updates

composer.lock
This PR updates PHPUnit to version 6.5.7, including dependencies.
* sebastian/comparator (2.1.0 => 2.1.3)
* doctrine/instantiator (1.0.5 => 1.1.0)
* phpunit/phpunit-mock-objects (5.0.5 => 5.0.6)
* webmozart/assert (1.2.0 => 1.3.0)
* phpdocumentor/reflection-docblock (4.2.0 => 4.3.0)
* phpspec/prophecy (1.7.3 => 1.7.5)
* phpunit/phpunit (6.5.4 => 6.5.7)
=> Updated PHPUnit to 6.5.7

composer.lock
This PR updates PHP CS Fixer to 2.10.4, including dependencies.
* php-cs-fixer/diff (v1.2.0 => v1.3.0)
* doctrine/annotations (v1.4.0 => v1.6.0)
* friendsofphp/php-cs-fixer (v2.10.2 => v2.10.4)
=> Updated PHP CS Fixer to 2.10.4

composer.lock
This PR updates infection to 0.7.1, including dependencies.
* pimple/pimple (v3.2.2 => v3.2.3)
* composer/ca-bundle (1.1.0)
* padraic/humbug_get_contents (1.0.4 => 1.1.2)
* padraic/phar-updater (1.0.4 => v1.0.5)
* nikic/php-parser (v3.1.2 => v3.1.5)
* infection/infection (0.7.0 => 0.7.1)
=> Updated Infection to 0.7.1

README.md
=> Fix #1120: Add note that command "bin/console server:start" is only available in application mode development

classes/Http/Form/SignupForm.php, tests/Unit/Http/Form/SignupFormTest.php
This PR addresses #1119.
The joind.in username validation is relatively [permissive](https://github.com/joindin/joindin-web2/blob/master/app/src/User/RegisterFormType.php#L42), only checking that it's not blank and it's a maximum of 100 characters. Without spinning up a joind.in instance, I wasn't comfortable testing their site for possible usernames (emoji, other special characters), hence why I'm still relatively restrictive in this PR.
=> Updates the regex for joind.in to better match valid characters

.gitignore, Homestead.yaml.example, README.md, Vagrantfile, after.sh, aliases, composer.json, composer.lock
Add [laravel/homestead](http://laravel.com/docs/homestead) as a local development option.
After running `$ script/setup` from the project root run `php vendor/bin/homestead make`. This will create a `Homestead.yaml` based on settings from `Homestead.yaml.example`. Do not version control `Homestead.yaml`
Run `vagrant up`
Add `192.168.10.10 opencfp.test` to your operating system's hosts file (/etc/hosts)
Point your browser to `http://opencfp.test`
Edit your `config/development.yml` to use Homestead's database & mail settings:
```
database:
host: 127.0.0.1
database: cfp
dsn: mysql:dbname=cfp;host=127.0.0.1
user: homestead
password: secret
log:
level: debug
mail:
host: localhost
port: 1025
username: ~
password: ~
encryption: ~
auth_mode: ~
```
Mailhog (local mail catching) can be viewed at …
=> ✨ first draft of adding homestead for local development

resources/views/layouts/splash.twig
Using site.show_contrib_banner parameter on splash layout for enable/disable fork me banner on signup, login and forgot_password pages.
=> Using show_contrib_banner parameter on splash layout

src/Environment.php, tests/Unit/EnvironmentTest.php
This PR
Fixes #1151.
💁‍♂️ Apologies for the clunky work - on vacation and working from an iPad.
=> Fix: Default to production when environment could not be determined from environment variable

composer.json, composer.lock
This PR upgrades some symfony components with security vulnerabilities. opencfp might not be affected at all.
https://symfony.com/blog/cve-2018-14773-remove-support-for-legacy-and-risky-http-headers
https://symfony.com/cve-2018-11386
https://symfony.com/cve-2018-11407
https://symfony.com/cve-2018-11406
I added a conflict for symfony/security-core higher than v4 for the possibility 
to release a patch version.
=> upgrade some symfony components

phinx.php, phpunit.xml.dist
In `script/test` the `CFP_ENV` is passed via envirmoment variable. `phinx.php` should only be used on cli anyway.
=> phinx: CFP_ENV is passed via enviroment variable instead of $_SERVER

src/Http/Form/SignupForm.php, tests/Unit/Http/Form/SignupFormTest.php
This PR fixes #1161 by permitting periods to be present in the joind.in link.
=> Allow for periods to be present in the joind.in username

resources/views/security/signup.twig, src/Domain/Services/Authentication.php, src/Http/Action/Security/LogInAction.php, src/Infrastructure/Auth/SentinelAuthentication.php, tests/Integration/Http/Action/Security/LogInActionTest.php, tests/Integration/Infrastructure/Auth/SentinelAuthenticationTest.php, tests/Unit/Infrastructure/Auth/SentinelAuthenticationTest.php
This PR addresses #1091 by redirecting users who attempt to log in with an email address that is not present in the system to the signup page, while also pre-populating the email field. It also validates that some semblance of an email address is provided, and keeps the user on the login page if not.
=> Redirects users with emails not in the system to the signup page

resources/config/routing.yml
=> Fix: Remove extra empty lines

resources/views/admin/speaker/index.twig, resources/views/admin/speaker/view.twig, resources/views/reviewer/speaker/index.twig, resources/views/reviewer/speaker/view.twig, src/Domain/Speaker/SpeakerProfile.php, tests/Unit/Domain/Speaker/SpeakerProfileTest.php
This PR
Related to the suggestion in https://github.com/opencfp/opencfp/pull/1166/files#r223808752.
/cc @chrisforrence
=> Enhancement: Move responsibilty to construct Twitter URL upstream

tests/Unit/Domain/Speaker/SpeakerProfileTest.php
This PR
Follows #1172.
Follows #1176.
=> Fix: Add missing test annotation

.travis.yml, Makefile, phpunit.xml.dist, tests/AutoReview/SrcCodeTest.php, tests/AutoReview/TestCodeTest.php
This PR
💁‍♂️ In addition to what we already have it could probably be useful to verify test code in regard to `public` methods that are not used as data providers and aren't prefixed with `test` (perhaps they should be tests and are missing a `@test` annotation)
=> Enhancement: Extract AutoReview test-suite and split tests

resources/views/admin/speaker/view.twig, resources/views/reviewer/speaker/view.twig
Fixes inconsistency where speaker bio can be Markdown formatted but additional info can't be, despite ostensibly having that ability (see input box hint).
=> Markdown-format additional speaker info

resources/views/admin/speaker/view.twig
Was tired of looking at &amp; every time a talk included a literal & in it.
=> Don't double-escape talk titles on speaker view

.php_cs.dist, src/Domain/Model/Favorite.php, src/Domain/Model/TalkComment.php, src/Domain/Model/TalkMeta.php, src/Environment.php, tests/Unit/Application/SpeakersTest.php
This PR
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/v2.10.2#usage:
> **visibility_required** [`@PSR2`, `@Symfony`, `@PHP71Migration`]
>
>Visibility MUST be declared on all properties and methods; abstract and final MUST be declared before the visibility; static MUST be declared after the visibility.
>
>
>* `elements` (`array`): the structural elements to fix (PHP >= 7.1 required for `const`); defaults to `['property', 'method']`
=> Enhancement: Configure visibility_required fixer

resources/views/talk/view.twig
As a speaker, I've wanted to access the additional talk info after the CFP has closed, but post-new-theme that info has been hidden, as it's only been available on the edit page (which of course goes away post CFP close).
Fingers crossed that this gets merged quickly, so I can start bugging other organizers to cherry-pick it into their forks (and so confs pulling from master will get it), so I'll be able to see that information on their confs for my talks :). Naturally, Longhorn has this bit already built in.
=> Show additional talk info on speaker view (post-conf-close)

config/testing.yml.dist
This PR addresses #1194 by setting the CFP closing date for testing far into the future (which was causing issues when testing if talks could be edited).
cc @chartjes
=> Set testing CFP close date to far into future

resources/views/admin/talks/view.twig, resources/views/reviewer/talks/view.twig, tests/Integration/Http/Action/Talk/EditActionTest.php
Otherwise they get formatted as plain text, losing spacing etc.
=> Markdown-format talk comments

resources/config/config.yml, resources/views/emails/talk_submit.twig, src/Domain/Services/ResetEmailer.php, src/Http/Action/Talk/CreateProcessAction.php, src/Http/Action/Talk/UpdateAction.php, src/Infrastructure/Templating/Template.php
Everything else uses the global date format, so it looks like this is a bit of an omission as it stands.
=> Use global date format for CFP end date in submission email

README.md, web/index.php
eg Cloudflare, kubernetes ingresses etc
Going to tidy up and test this tomorrow, putting in a PR as a reminder
=> Add an option to trust headers set by reverse proxies

migrations/20181002234013_create_user_joind_in_username_column.php
=> Fixed joind in username column migration

resources/views/admin/talks/view.twig, resources/views/reviewer/speaker/view.twig, resources/views/reviewer/talks/view.twig, resources/views/talk/view.twig
This PR simply adds a raw filter to the talk titles where it is missing.
Fixes #1217.
=> Add raw filter to talk titles

config/development.yml.dist, config/docker.yml.dist, config/production.yml.dist, config/testing.yml.dist, resources/config/services/domain.yml, resources/views/dashboard.twig, resources/views/forms/_user.twig, src/Domain/Services/ProfileImageProcessor.php, src/Infrastructure/Templating/TwigExtension.php
This PR removes the hard-coded image resize (250px) and allows it to be configured at the application configuration level. Furthermore, this also allows the application to generate 240x240 thumbnails to be used on the dashboard (instead of cramming a potentially-large file into a 120x120 space). If a thumbnail is not available for a particular image, an onerror handler swaps the image source out with the non-thumbnail version.
Related to #1199.
=> Adds the ability to store larger uploaded files

package.json
This PR upgrades tailwindcss to version 0.7.4 to match the avaliable docs https://v0.tailwindcss.com/docs/what-is-tailwind/
=> upgrade tailwind to version 0.7.4

README.md
This PR adds a port to the docker-compose section of the README.
When using the default `docker-compose.yml.dist` file, port 8080 is used instead of 80.
=> Add port in README for the default docker-compose

.php_cs.dist, migrations.php, tests/Integration/Domain/Model/UserTest.php, tests/Integration/Http/Action/Admin/Speaker/PromoteActionTest.php
This PR
Fixes cs errors that were presented by running `make cs`.
Migrations are added on the exclude list since they are generated via command.
=> fixing cs errors and adding migrations on exclude list

resources/views/package.twig
I can't remember the last time I saw a VGA cable connected to a projector, or a laptop that had a VGA port or adapter.  I also haven't seen a conference organizer change this sentence _ever_.
And maybe check back in a few years to see how USB-C/Thunderbolt 3 is doing.
=> Update verbiage on speaker package page

resources/config/config_development.yml, resources/config/config_production.yml
Currently speakers list doesn't work if database isn't default one.
=> Fix configs to use credentials defined in parameters instead of hardcoded ones

config/ci.yml.dist, config/development.yml.dist, config/docker.yml.dist, config/production.yml.dist, config/testing.yml.dist, resources/views/reviewer/index.twig, resources/views/reviewer/talks/index.twig, resources/views/reviewer/talks/view.twig, tests/Integration/Http/Action/Reviewer/DashboardActionTest.php, tests/Integration/Http/Action/Reviewer/Talk/IndexActionTest.php, tests/Integration/Http/Action/Reviewer/Talk/ViewActionTest.php, tests/Integration/WebTestCase.php
Some conferences have attempted to remove a source of bias in speaker selection by hiding the names of speakers from reviewers. This PR introduces a new configuration option to enable this behavior. The default behavior is unchanged, so it is an opt-in solution for users.
Fixes #1075.
=> Implements and tests anonymized reviews setting
