classes/OpenCFP/Application.php
tests/unit/controllers/SignupControllerTest.php

Wrote test in response to issue179, was a good exercise in figuring out correct mocking of the Application object to remove dependencies on using the database in the unit tests.

Added unit test for Signup controller

---

README.md
composer.json
templates/layouts/default.twig

Noticed this working on #184. A `sed` replace later... :smile:

Removes remaining references to previous repository location.

---

.htaccess
README.md
classes/OpenCFP/Http/Controller/Admin/SpeakersController.php
composer.json

A few items required for functionality.

Symfony/security-csrf add, ENV add, date formats, and readme update

---

classes/OpenCFP/Domain/Entity/Mapper/Talk.php
tests/OpenCFP/Domain/Entity/Mapper/TalkTest.php

CodeClimate indicated the method was missing any coverage at all for that method

Added in test for getAdminFavorites method in the Talk mapper

---

classes/OpenCFP/Console/Application.php
classes/OpenCFP/Console/Command/AdminDemoteCommand.php
classes/OpenCFP/Console/Command/AdminPromoteCommand.php

Add global --env option. Fix issue #208.

---

.travis.yml

This PR
:information_desk_person: This should speed up builds, see http://docs.travis-ci.com/user/workers/container-based-infrastructure/.

Enhancement: Use container-based infrastructure on Travis

---

config/development.dist.yml

See https://github.com/opencfp/opencfp/blob/master/phinx.yml.dist#L14-L19

Update default dev config to match phinx

---

classes/ContainerAware.php

Fix: Reduce visibility of instance property

---

classes/Domain/Entity/Mapper/Talk.php
classes/Http/Controller/Admin/ExportsController.php
classes/Http/Controller/Admin/TalksController.php
classes/Provider/Gateways/WebGatewayProvider.php
templates/layouts/admin.twig

Closes #257
Sample CSVs: https://www.dropbox.com/sh/e1pfioq7fcjmli0/AADUx-0_txio4iqhmS-Gszgaa?dl=0
This allows for:
* A full list of talks complete with speaker info (one talk a row)
* A full list of talks anonymised (Speaker info fields, slides and 'More Information' removed)
* A list of all talk names, whether they were selected, speaker names and emails for use in sending acceptance/rejection emails
* A list of all selected talks with full information including speaker info
What must be done before merge
There is some neatening up that should probably be done but this is fully functional and I'm not sure if/when I'll have a chance to neaten it up so if someone wants to continue this feel free. I can certainly add on a revised navigation icon however if someone can make the icon (I'm no …

Export feature

---

config/development.dist.yml
config/production.dist.yml
config/testing.yml
templates/dashboard.twig
templates/forms/_user.twig

The request was to make it so that information about airport and hotel could be hidden, so I added a confg value (set to be false by default) if the conference is an online one.

Fixed issue #207

---

.travis.yml

Fix: Collect and report coverage on PHP7 only

---

.travis.yml

This PR
Follows https://github.com/opencfp/opencfp/pull/300#issuecomment-166194054.

Fix: Introduce COLLECT_COVERAGE environment variable

---

tests/OpenCFP/Domain/Services/LoginTest.php

Fix: Cover Domain\Services\Login

---

tests/OpenCFP/Domain/Speaker/SpeakerProfileTest.php

Fix: Partially cover Domain\Speaker\SpeakerProfile

---

templates/admin/speaker/view.twig
templates/dashboard.twig
tests/unit/controllers/DashboardControllerTest.php

removing transportation and hotel display on dashboard if online conference is selected
removing twitter link if empty

online conference dashboard fix

---

classes/Http/Controller/TalkController.php
tests/unit/controllers/TalkControllerTest.php

Original PR: #337 
This PR carries-forward the work done by @michaelcullum in the above-referenced patch. I had to rebase his changes onto `upstream/master` because of a problem introduced into the test-suite by myself. Rather than ask Michael to pull my commits in and then risk re-introduction of my mistake, I am creating a separate PR that includes Michael's patch and adds a relevant test.

Add tests and rebase #337 onto `master`.

---

CONTRIBUTING.md

Old PR: #261 
Related: #307 "Tests need to be sorted out"
We created this before and accidentally closed the pull request instead of merging, leaving un-merged commits. This PR revives that work and adds to it; reflecting changes and improvements to contributor workflow since it was originally created.

Add Contributor Documentation, ROUND 2!

---

README.md

Based on conversation in #355 and thanks to @pmeth's example I was able to get email working in ~20 minutes (after spending several hours last night with no luck) so I thought this might be helpful to others.

Add email config example

---

tests/Http/Controller/DashboardControllerTest.php

Fix: Remove unused imports

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

This PR
:information_desk_person: For reference, see https://github.com/blog/2111-issue-and-pull-request-templates.

Enhancement: Leverage GitHub issue and pull request template capabilities

---

tests/Domain/Services/ResetEmailerTest.php

Fix: Increase legibility of test

---

classes/Console/Command/ClearCacheCommand.php

This PR
Somewhat related to #380.

Fix: Simplify clearing caches

---

classes/Http/API/ApiController.php
classes/Http/Controller/Admin/AdminsController.php
classes/Http/Controller/Admin/DashboardController.php
classes/Http/Controller/Admin/ExportsController.php
classes/Http/Controller/Admin/ReviewController.php
classes/Http/Controller/Admin/SpeakersController.php
classes/Http/Controller/Admin/TalksController.php
classes/Http/Controller/BaseController.php
classes/Http/Controller/DashboardController.php
classes/Http/Controller/ForgotController.php
classes/Http/Controller/PagesController.php
classes/Http/Controller/ProfileController.php
classes/Http/Controller/SecurityController.php
classes/Http/Controller/SignupController.php
classes/Http/Controller/TalkController.php

This PR
@mdwheele Not sure in which PR, but I think we briefly talked about streamlining this some time ago, what do you think?

Fix: Retrieve services using service()

---

README.md
script/bootstrap
script/server
script/setup
script/test
script/update
server.php

This PR adds the Scripts to Rule Them All pattern, https://github.com/github/scripts-to-rule-them-all,  to allow for a more simplified development experience. Also, I've included a server.php router file for PHP built-in web server. I have re-organized the README to move local development higher up and created an entire section for Scripts to Rule Them All.
Related to #262

Scripts to Rule Them All (PHP built-in web server support)

---

classes/Http/Form/TalkForm.php
migrations/20150702132854_fix_defaults_for_users_table.php
tests/Http/Form/TalkFormTest.php

This PR fixes the internal server error for talk submissions when not selecting best talk or sponsor.
Fixes #406

Fix talk submission

---

classes/Http/Controller/TalkController.php
classes/Http/Form/TalkForm.php
config/development.dist.yml
config/production.dist.yml
templates/forms/_talk.twig
tests/Http/Form/TalkFormTest.php

Moves talk categories into config to enable easier modification

---

README.md
classes/Http/Controller/SignupController.php
classes/Http/Form/SignupForm.php
config/production.dist.yml
templates/forms/_user.twig
tests/Http/Controller/SignupControllerTest.php

This PR
The field is only enabled if the admin provides a link to the code of conduct in the config file; previous behaviour is maintained unless this link is defined.

Adds a signup field requring users to agree to the code of conduct

---

README.md
classes/Http/Controller/TalkController.php
classes/Http/Form/TalkForm.php
classes/Http/View/TalkHelper.php
classes/Provider/TwigServiceProvider.php
config/development.dist.yml
config/production.dist.yml
templates/admin/talks/_table.twig
templates/admin/talks/view.twig
templates/dashboard.twig
templates/forms/_talk.twig
templates/talk/view.twig
tests/Http/Form/TalkFormTest.php

This PR
Fixes #254.
Relates to #411

Move talk lengths to config

---

README.md
classes/Http/Controller/TalkController.php
classes/Http/Form/TalkForm.php
classes/Http/View/TalkHelper.php
classes/Provider/TwigServiceProvider.php
config/development.dist.yml
config/production.dist.yml
templates/admin/talks/_table.twig
templates/admin/talks/view.twig
templates/dashboard.twig
templates/forms/_talk.twig
templates/talk/view.twig
tests/Http/Form/TalkFormTest.php

Revert "Move talk lengths to config"

---

classes/Domain/Entity/Mapper/Talk.php
templates/layouts/admin.twig

Revert "Fixes #391"

---

config/testing.yml

Fix issue causing unit test failiures

---

README.md
classes/Http/Controller/TalkController.php
classes/Http/Form/TalkForm.php
classes/Http/View/TalkHelper.php
classes/Provider/TwigServiceProvider.php
config/development.dist.yml
config/production.dist.yml
templates/admin/talks/_table.twig
templates/admin/talks/view.twig
templates/dashboard.twig
templates/forms/_talk.twig
templates/talk/view.twig
tests/Http/Form/TalkFormTest.php

Reverts opencfp/opencfp#418
Unit test failure had nothing to do with this PR - fixed separatly

Revert "Revert "Move talk lengths to config""

---

classes/Domain/Entity/Mapper/Talk.php
templates/layouts/admin.twig

Reverts opencfp/opencfp#417
Unit test failure had nothing to do with this PR - fixed separatly

Revert "Revert "Fixes #391""

---

classes/Console/Command/AdminDemoteCommand.php
tests/Console/ApplicationTest.php

r? @mdwheele 
This PR is adding test coverage to the AdminDemote console command

Added tests for AdminDemote command to get 100% coverage

---

classes/Application.php

This PR resolves the issue #424

Move timezone set before register TwigServiceProvider

---

phpunit.xml.dist

This PR
💁‍♂️ This helps with auto-completion when modifying the configuration file!

Enhancement: Reference XML schema for phpunit.xml

---

classes/Http/Controller/Admin/AdminsController.php
classes/Http/Controller/Admin/SpeakersController.php
classes/Provider/Gateways/WebGatewayProvider.php
templates/admin/speaker/index.twig

This PR
* Added a promoteAction method on AdminsController
* Updated SpeakersController's index method for finding Admin grouped users.
* Updated speaker/index template for showing Admin Grouped users or their promoting links.
* Updated WebGateWayProvider for define promoting URL

Enhancement: Promoting as an Admin on Speakers Page

---

.codeclimate.yml

Add a Code Climate config with PHP Code Sniffer (PSR2 standards enabled) and our duplication engine. 
@chartjes

Code Climate config with PHP Code Sniffer and duplication

---

tests/Console/ApplicationTest.php
tests/EnvironmentTest.php
tests/Http/Form/LoginTest.php

This PR
* Adds a new test for the Environment class
* Adds a test to check OpenCFP\Console\Application's getContainer method
* Adds a test to check the OpenCFP\Http\Form\Login object

Adds new units tests and makes one test less brittle

---

classes/Http/Controller/TalkController.php

Fixes #461

---

classes/Domain/Entity/Mapper/Talk.php
classes/Domain/Services/Login.php
classes/Http/Controller/Admin/ExportsController.php

Fix: Remove unnecessary parentheses

---

classes/Http/Form/SignupForm.php
tests/Http/Form/Entity/LoginTest.php
tests/Http/Form/Entity/ProfileTest.php
tests/Http/Form/Entity/UserTest.php
tests/Http/Form/LoginTest.php
tests/Http/Form/ResetFormTest.php
tests/Http/Form/SignupFormTest.php

This PR
* Adds new tests for the SignupForm class and fixes a minor issue 
* Adds missing 'parent::setUp' calls in a few test fixtures
Comment : 60.54% code coverage.
Follows N/A.
Related to N/A.
Fixes N/A.

Adds a few more tests

---

config/development.dist.yml
config/production.dist.yml

To be sure that you can test the app when installing it.

Change default dates

---

tests/ApplicationTest.php
tests/Console/AdminPromoteCommandTest.php
tests/Console/ApplicationTest.php
tests/Http/Controller/Admin/SpeakersControllerTest.php
tests/Http/Controller/Admin/TalksControllerTest.php
tests/Http/Controller/DashboardControllerTest.php
tests/Http/Controller/ForgotControllerTest.php
tests/Http/Controller/ProfileControllerTest.php
tests/Http/Controller/SignupControllerTest.php
tests/Http/Controller/TalkControllerTest.php
tests/Infrastructure/Auth/SentryAccountManagementTest.php
tests/Infrastructure/Auth/SentryAuthenticationTest.php
tests/Infrastructure/Persistence/IlluminateAirportInformationDatabaseTest.php

Adds db group annotation to all tests which fail without a configured db conection

---

classes/Domain/Entity/Mapper/Talk.php
classes/Http/Controller/Admin/TalksController.php
templates/admin/talks/index.twig

A left over one from last year rebased against latest master.
Allows admin users to pull back a list of the talks that they +1'd

Added new option to select +1 rated talks

---

classes/Domain/Entity/Mapper/User.php
classes/Http/Controller/Admin/SpeakersController.php
templates/admin/speaker/index.twig
tests/Domain/Entity/Mapper/UserTest.php

As the system gets more and more users it can become a bit annoying to find a specific speaker to either promote them to admin or check out their talks.
Right now it just searches through their first and last name, i'm not sure if it should be expanded to also include things like their bio/email/twitter etc.

Allow searching for specific speakers

---

classes/Provider/DatabaseServiceProvider.php
migrations/20140828144530_add_id_to_speaker_table.php
migrations/20141121173412_add_talk_meta.php
migrations/20141122213222_create_talk_comment.php
migrations/20141201172522_alter_user_column_defaults.php
migrations/20141203111136_alter_talk_column_defaults.php
migrations/20150702132854_fix_defaults_for_users_table.php
migrations/20160106061843_fix_zero_dates.php
tests/DatabaseTestCase.php

* made them database-agnostic
* removed method that checks if the database isn't working that was MySQL specific

Database migration changes

---

classes/Http/Controller/Admin/TalksController.php
classes/Http/Form/Form.php

This PR fixes some errors that came from all these PR's.
- Fixed the view action function, since it was a mix of spot and illuminate for a bit.
- Renamed the second sanitize function to internalSanitize to stop the errors.

Fix merging errors

---

composer.json
composer.lock

This PR
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/compare/v2.7.1...v2.8.0 - especially take note of added fixers in [`README.rst`](https://github.com/FriendsOfPHP/PHP-CS-Fixer/compare/v2.7.1...v2.8.0#diff-88b99bb28683bd5b7e3a204826ead112).

Enhancement: Update friendsofphp/php-cs-fixer

---

.travis.yml

Enhancement: Add asset stage

---

tests/Domain/Entity/Mapper/UserTest.php
tests/Domain/Services/ResetEmailerTest.php
tests/TestResponse.php

Fix: Use more appropriate assertions

---

classes/Console/Command/AdminDemoteCommand.php
classes/Domain/Entity/Mapper/Talk.php
classes/Http/API/ApiController.php
classes/Http/API/TalkController.php
tests/TestResponse.php
tests/WebTestCase.php

Fix: Undefined classes

---

.travis.yml

This PR
* updates the Travis settings to provide support for code coverage messages to be sent

Update test coverage settings

---

classes/Http/Controller/Admin/SpeakersController.php

This PR removes some references to the old admin access trait.

Remove old userHasAccess calls

---

classes/Http/Controller/Admin/SpeakersController.php

This PR simplifies the is_admin check for the speakers overview

Simplify the is admin check

---

classes/Http/Controller/PagesController.php

This PR updates the Pagescontroller

Refactor: PagesController to use illuminate

---

classes/Http/Controller/ProfileController.php
tests/Http/Controller/ProfileControllerTest.php

Profile controller now uses Illuminate instead of spot, and updated tests for the new behavior. 
Related to #506.

Refactor: Profile controller to use Illuminate

---

.php_cs
tests/Http/Controller/TalkControllerTest.php

Revert "Enhancement: Enable cast_spaces fixer"

---

.travis.yml
.travis/xdebug.sh

Enhancement: Disable xdebug and enable only when needed

---

tests/Http/Controller/SignupControllerTest.php

This PR updates the signup controller test to the new format.

Fix: Update sign up controller tests

---

.gitignore
infection.json.dist

This PR updates the infection settings
Follows #606

Update infection settings

---

classes/Http/Controller/Admin/SpeakersController.php
resources/views/admin/speaker/index.twig
tests/Http/Controller/Admin/SpeakersControllerTest.php

This PR adds the option to add reviewers through the GUI, instead of just with the commandline
Follows #556, #576 .

Enhancement: Make reviewers in gui

---

tests/ApplicationTest.php
tests/Domain/Model/TalkTest.php
tests/Domain/Model/UserTest.php
tests/Domain/Services/PaginationTest.php
tests/EnvironmentTest.php
tests/Http/Controller/PagesControllerTest.php
tests/Infrastructure/Persistence/IlluminateSpeakerRepositoryTest.php

This PR adds some tests, and updates some to be more accurate

Enhancement: more tests

---

classes/Http/Controller/Admin/ExportsController.php
classes/Http/Controller/BaseController.php
tests/Http/Controller/Admin/ExportsControllerTest.php

This PR changes the exports controller to use the Response object.

Refactor: Exports controller

---

classes/Console/Application.php
classes/Domain/Model/Talk.php
classes/Domain/Services/ProfileImageProcessor.php
classes/Http/Form/Form.php
classes/Http/View/TalkHelper.php
classes/Provider/Gateways/RequestCleaner.php
tests/Console/AdminPromoteCommandTest.php
tests/Console/ApplicationTest.php
tests/Http/Controller/Admin/SpeakersControllerTest.php
tests/Http/Controller/DashboardControllerTest.php
tests/Http/Controller/ForgotControllerTest.php
tests/Http/Controller/ProfileControllerTest.php
tests/Http/Controller/SignupControllerTest.php
tests/Http/Controller/TalkControllerTest.php
tests/Infrastructure/Auth/SentryAccountManagementTest.php
tests/Infrastructure/Auth/SentryAuthenticationTest.php

Fix: Remove comments that state the obvious

---

PHPMDRuleSet.xml
classes/Application.php
classes/Console/Command/ClearCacheCommand.php
classes/Environment.php
classes/Path.php
classes/Provider/HtmlPurifierServiceProvider.php
classes/Provider/ImageProcessorProvider.php
classes/Provider/TwigServiceProvider.php
tests/PathTest.php
tests/Unit/ApplicationTest.php
tests/Unit/EnvironmentTest.php
tests/Unit/PathTest.php

This PR separates the functionality some functionality out of the Application class

Enhancement: Separate path and environment from application

---

classes/Environment.php

This PR
Somewhat related to #635.
/cc @BackEndTea

Fix: Add type declarations

---

classes/Application/Speakers.php
classes/Domain/Model/Airport.php
classes/Domain/Model/User.php
classes/Domain/Services/Authentication.php
classes/Domain/Services/IdentityProvider.php
classes/Domain/Services/ProfileImageProcessor.php
classes/Http/API/TalkController.php
classes/Infrastructure/Auth/OAuthIdentityProvider.php
classes/Infrastructure/Auth/SentryAuthentication.php
classes/Infrastructure/Auth/SentryIdentityProvider.php

Fix: Run 'make cs'

---

tests/Unit/Application/NotAuthorizedExceptionTest.php
tests/Unit/Domain/EntityNotFoundExceptionTest.php
tests/Unit/Domain/Services/NotAuthenticatedExceptionTest.php
tests/Unit/Domain/Services/TalkRating/TalkRatingExceptionTest.php
tests/Unit/Domain/Speaker/NotAllowedExceptionTest.php
tests/Unit/Domain/Talk/InvalidTalkSubmissionExceptionTest.php
tests/Unit/Domain/ValidationExceptionTest.php

Fix: Cover yet uncovered exceptions

---

infection.json.dist

Update infection to use the new tests

---

classes/Environment.php

Fix: Simplify comparison

---

classes/Environment.php
tests/Unit/EnvironmentTest.php

Enhancement: Extract constants for environment types

---

classes/Environment.php
tests/Unit/EnvironmentTest.php

Enhancement: Improve exception message

---

classes/Environment.php
tests/Unit/EnvironmentTest.php

Fix: Rename field, parameter, variable

---

classes/Environment.php
tests/Unit/EnvironmentTest.php

Fix: Merge conflict

---

tests/Unit/EnvironmentTest.php

Fix: Split and merge tests

---

classes/Environment.php

This PR
💁‍♂️ Docblocks add value as the exceptions thrown are now visible.

Fix: Add missing docblocks

---

tests/Helper/Faker/GeneratorTrait.php
tests/Helper/RefreshDatabase.php
tests/Helper/SentryTestHelpers.php
tests/Integration/Domain/Model/AirportTest.php
tests/Unit/Http/Form/SignupFormTest.php
tests/Unit/Http/Form/TalkFormTest.php

Fix: Use return type declarations

---

tests/Unit/Http/API/ProfileApiControllerTest.php
tests/Unit/Http/API/TalkApiControllerTest.php
tests/Unit/Infrastructure/Auth/SentryIdentityProviderTest.php

Fix: Undefined class

---

tests/Unit/Http/API/ApiControllerTest.php
tests/Unit/Http/API/StubApiController.php

Fix: Remove unneeded stub

---

tests/Integration/Http/Controller/DashboardControllerTest.php
tests/TestResponse.php
tests/WebTestCase.php

Fix: Use type declarations

---

.php_cs
classes/Http/Form/SignupForm.php
classes/Http/OAuth/AuthorizationController.php
tests/helpers.php

This PR
>**no_useless_else**
>
>There should not be useless else cases.

Enhancement: Enable no_useless_else fixer

---

README.md

Removed references to screenshots

---

classes/Domain/Services/TalkRating/TalkRating.php
classes/Domain/Services/TalkRating/TalkRatingStrategy.php
classes/Domain/Services/TalkRating/YesNoRating.php
tests/Unit/Domain/Services/TalkRating/TalkRatingContextTest.php
tests/Unit/Domain/Services/TalkRating/TalkRatingTest.php
tests/Unit/Domain/Services/TalkRating/YesNoRatingTest.php

Improve TalkRating

---

.php_cs.dist
.travis.yml

Improve PHP CS Fixer <> Travis integration

---

package.json

This PR
💁‍♂️ Not sure why it's there, but it works fine without it.

Fix: Remove unnecessary prefix

---

config/development.dist.yml
config/production.dist.yml
config/testing.yml
resources/views/layouts/default.twig

The contribution banner is now toggle-able

---

classes/Domain/CallForProposal.php
classes/Provider/ApplicationServiceProvider.php
tests/Integration/Http/Controller/TalkControllerTest.php
tests/Unit/Domain/CallForProposalTest.php

Fix: Modify type declaration to DateTimeImmutable

---

classes/ContainerAware.php

This PR
Somewhat related to #714.

Fix: Add type declaration

---

resources/views/layouts/admin.twig

Fix: Spelling

---

classes/Path.php

Fix: Use field directly

---

classes/Domain/Talk/InvalidTalkSubmissionException.php
classes/Domain/Talk/TalkSubmission.php
tests/Unit/Domain/Talk/InvalidTalkSubmissionExceptionTest.php

Enhancement: Extract named constructors

---

resources/views/user/reset_password.twig

Fixed bad layout include

---

tests/Unit/Infrastructure/Persistence/IlluminateSpeakerRepositoryTest.php

Fix: Cover repository

---

classes/Domain/Speaker/SpeakerRepository.php
classes/Infrastructure/Persistence/IlluminateSpeakerRepository.php
classes/Infrastructure/Persistence/IlluminateTalkRepository.php

This PR
Follows #744.
Follows #745.

Fix: Docblocks

---

classes/Domain/Speaker/SpeakerProfile.php

Fix: Add docblocks

---

classes/Infrastructure/Auth/SentinelAccountManagement.php
classes/Infrastructure/Auth/SentryAccountManagement.php
classes/Infrastructure/Auth/UserExistsException.php
tests/Unit/Infrastructure/Auth/UserExistsExceptionTest.php

Enhancement: Create named constructor for UserExistsException

---

classes/Domain/Speaker/SpeakerProfile.php
tests/Unit/Domain/Speaker/SpeakerProfileTest.php

Fix: Compare strictly

---

classes/Application.php

Fix: Remove unnecessary assignment

---

classes/Domain/Services/ResetEmailer.php
classes/Http/Controller/Admin/DashboardController.php
classes/Http/Controller/Admin/SpeakersController.php
classes/Http/Controller/Admin/TalksController.php
classes/Http/Controller/ForgotController.php
classes/Http/Controller/ProfileController.php
classes/Http/Controller/Reviewer/DashboardController.php
classes/Http/Controller/Reviewer/TalksController.php
classes/Http/Controller/SecurityController.php
classes/Http/Controller/TalkController.php
classes/Http/Form/Form.php
classes/Http/Form/SignupForm.php
classes/Http/Form/TalkForm.php
migrations/20140902174929_remove_speaker_table.php
migrations/20171120122725_roles_migration.php
tests/Integration/Http/Controller/ForgotControllerTest.php
tests/Integration/Http/Controller/SignupControllerTest.php
tests/Integration/Http/Controller/TalkControllerTest.php

Fix: Use camelCase for fields and variables

---

classes/Path.php
classes/PathInterface.php
tests/Unit/PathTest.php

This PR
💁‍♂️ Need this for decoupling the `ClearCacheCommand` from the application container.

Enhancement: Extract PathInterface

---

tests/Integration/Domain/Model/AirportTest.php

This PR
Somewhat related to #796.

Fix: Inline method

---

classes/Domain/Services/AuthenticationException.php
classes/Infrastructure/Auth/SentinelAuthentication.php
tests/Unit/Domain/Services/AuthenticationExceptionTest.php

Enhancement: Extract dedicated constructor

---

classes/Http/Controller/DashboardController.php
classes/Http/Controller/SignupController.php
classes/Http/Controller/TalkController.php
classes/Provider/CallForPapersProvider.php
classes/Provider/Gateways/WebGatewayProvider.php
tests/Integration/Http/Controller/TalkControllerTest.php
tests/WebTestCase.php

This PR
Both these changes make this provider work more like all the other providers.

Enhancement: Update CFP provider

---

classes/Domain/Services/AccountManagement.php
classes/Infrastructure/Auth/SentinelAccountManagement.php

Add type declarations to the AccountManagement interface

---

classes/Console/Application.php
classes/Console/Command/ClearCacheCommand.php
composer.json
composer.lock
tests/Unit/Console/ApplicationTest.php
tests/Unit/Console/Command/ClearCacheCommandTest.php

Enhancement: Decouple ClearCacheCommand from application container

---

classes/Application/Speakers.php

Fix: Wrapping

---

.php_cs.dist
bin/opencfp

Enhancement: Include bin/opencfp in php-cs-fixer configuration

---

README.md

Fix: Instructions for promoting and demoting users

---

classes/Infrastructure/Auth/SentinelAuthentication.php

Fix: Remove docblocks

---

classes/Domain/Services/Authentication.php
classes/Infrastructure/Auth/SentinelAuthentication.php
tests/Integration/Infrastructure/Auth/SentinelAuthenticationTest.php
tests/Unit/Infrastructure/Auth/SentinelAuthenticationTest.php

Fix: Remove unused method

---

classes/Http/Controller/Admin/SpeakersController.php
classes/Http/Controller/Admin/TalksController.php
classes/Http/Controller/ForgotController.php
classes/Http/Controller/ProfileController.php
classes/Http/Controller/Reviewer/SpeakersController.php
classes/Http/Controller/Reviewer/TalksController.php
classes/Http/Controller/SecurityController.php
classes/Http/Controller/SignupController.php
classes/Http/Controller/TalkController.php
tests/Integration/Http/Controller/ForgotControllerTest.php

This PR
💁‍♂️ There's no benefit in abbreviating.

Fix: Rename $req to $request

---

classes/Provider/ControllerResolver.php

This PR
Related to https://github.com/opencfp/opencfp/pull/850#issuecomment-349365995.

Fix: Simplify ControllerResolver

---

classes/Http/Controller/Admin/DashboardController.php
classes/Http/Controller/DashboardController.php
classes/Http/Controller/Reviewer/DashboardController.php
classes/Provider/Gateways/WebGatewayProvider.php
tests/Integration/Http/Controller/DashboardControllerTest.php

Dashboard controllers are being constructed via DI.
Follows #855.

Removed ContainerAware from dashboard controllers

---

classes/Http/Controller/ForgotController.php
classes/Provider/Gateways/WebGatewayProvider.php
tests/Integration/Http/Controller/ForgotControllerTest.php

The `ForgotController` is being constructed via DI.
Follows #855.

Removed ContainerAware from ForgotController

---

classes/Http/Controller/ProfileController.php
classes/Provider/Gateways/WebGatewayProvider.php

The `ProfileController` is being constructed via DI.
Follows #855.

Removed ContainerAware from ProfileController

---

classes/Http/Controller/SecurityController.php
classes/Provider/Gateways/WebGatewayProvider.php

The `SecurityController` is being constructed via DI.
Follows #855.

Removed ContainerAware from SecurityController

---

classes/Http/Controller/SignupController.php
classes/Provider/Gateways/WebGatewayProvider.php

The `SignupController` is being constructed via DI.
Follows #855.

Removed ContainerAware from SignupController

---

classes/Http/Controller/Admin/SpeakersController.php
classes/Http/Controller/Reviewer/SpeakersController.php
classes/Provider/Gateways/WebGatewayProvider.php

Both `SpeakersController` classes are being constructed via DI.
Follows #855.

Removed ContainerAware from both SpeakersControllers

---

classes/Http/Controller/Admin/TalksController.php
classes/Http/Controller/Reviewer/TalksController.php
classes/Provider/Gateways/WebGatewayProvider.php

Both `TalksController` classes are being constructed via DI.
Follows #855.

Removed ContainerAware from both TalksControllers

---

classes/Http/Controller/Admin/DashboardController.php
classes/Http/Controller/Admin/SpeakersController.php
classes/Http/Controller/Admin/TalksController.php
classes/Http/Controller/ForgotController.php
classes/Http/Controller/ProfileController.php
classes/Http/Controller/Reviewer/DashboardController.php
classes/Http/Controller/Reviewer/SpeakersController.php
classes/Http/Controller/Reviewer/TalksController.php
classes/Http/Controller/SecurityController.php
classes/Http/Controller/TalkController.php

Fix: Inline data passed to render()

---

.github/CONTRIBUTING.md

Added some details about test contributions

---

classes/Provider/ApplicationServiceProvider.php
classes/Provider/CallForPapersProvider.php
classes/Provider/ControllerResolver.php
classes/Provider/ControllerResolverServiceProvider.php
classes/Provider/Gateways/RequestCleaner.php
classes/Provider/Gateways/WebGatewayProvider.php
classes/Provider/HtmlPurifierServiceProvider.php
classes/Provider/ImageProcessorProvider.php
classes/Provider/ResetEmailerServiceProvider.php
classes/Provider/TalkFilterProvider.php
classes/Provider/TalkHandlerProvider.php
classes/Provider/TalkHelperProvider.php
classes/Provider/TalkRatingProvider.php
classes/Provider/TwigServiceProvider.php
classes/Provider/YamlConfigDriver.php
tests/Unit/ProjectCodeTest.php

Fix: Make all providers final

---

tests/BaseTestCase.php

Fix: Reduce visibility

---

classes/Domain/Services/TalkFormat.php
classes/Domain/Talk/TalkFormatter.php

Fix: Remove unused parameter

---

resources/views/admin/speaker/index.twig
resources/views/forms/_talk.twig
resources/views/layouts/default.twig
resources/views/reviewer/speaker/index.twig

Fix: Include flash

---

classes/Http/Form/Form.php
classes/Http/Form/ResetForm.php
classes/Http/Form/SignupForm.php
classes/Http/Form/TalkForm.php

Fix: Clean up forms

---

tests/Unit/Http/View/TalkHelperTest.php
tests/Unit/ProjectCodeTest.php

Fix: Add tests for TalkHelper

---

classes/Http/Action/Talk/ViewAction.php
classes/Http/Controller/TalkController.php
classes/Provider/Gateways/WebGatewayProvider.php
tests/Integration/Http/Action/Talk/ViewActionTest.php
tests/Integration/Http/Controller/TalkControllerTest.php
tests/Unit/Http/Action/AbstractActionTestCase.php
tests/Unit/Http/Action/Talk/ViewActionTest.php

Enhancement: Extract ViewAction from TalkController

---

tests/Unit/Http/Action/Page/HomePageActionTest.php
tests/Unit/Http/Action/Page/SpeakerPackageActionTest.php
tests/Unit/Http/Action/Page/TalkIdeasActionTest.php

Fix: Adjust spacing

---

classes/Domain/Repository/UserRepository.php
classes/Infrastructure/Auth/SentinelIdentityProvider.php
classes/Infrastructure/Repository/IlluminateUserRepository.php
classes/Provider/ApplicationServiceProvider.php
tests/Unit/Infrastructure/Auth/SentinelIdentityProviderTest.php
tests/Unit/Infrastructure/Repository/IlluminateUserRepositoryTest.php

Fix: Rename and move repository

---

tests/Unit/Http/Action/DashboardActionTest.php
tests/Unit/Http/Action/Talk/ViewActionTest.php

This PR
Follows #912.
Follows #924.

Fix: Assert redirect url

---

classes/Http/Action/Talk/DeleteAction.php
classes/Http/Controller/TalkController.php
classes/Provider/Gateways/WebGatewayProvider.php
tests/Integration/Http/Action/Talk/DeleteActionTest.php
tests/Integration/Http/Controller/TalkControllerTest.php
tests/Unit/Http/Action/Talk/DeleteActionTest.php

Enhancement: Extract DeleteAction from TalkController

---

resources/views/forms/_talk.twig

Fix: Remove empty class attributes

---

classes/Http/Controller/ForgotController.php
classes/Http/Form/ForgotFormType.php
tests/Unit/ProjectCodeTest.php

This PR
Follows https://github.com/opencfp/opencfp/pull/964#discussion_r157432415.

Fix: Rename class

---

classes/Http/Action/Talk/CreateAction.php
classes/Http/Controller/TalkController.php
resources/config/routing.yml
tests/Integration/Http/Action/Talk/CreateActionTest.php
tests/Integration/Http/Controller/TalkControllerTest.php
tests/Unit/Http/Action/Talk/CreateActionTest.php

Enhancement: Extract CreateAction from TalkController

---

classes/Http/Action/Signup/IndexAction.php
classes/Http/Controller/SignupController.php
resources/config/routing.yml
tests/Integration/Http/Action/Signup/IndexActionTest.php
tests/Integration/Http/Controller/SignupControllerTest.php
tests/Unit/Http/Action/Signup/IndexActionTest.php

Enhancement: Extract IndexAction from SignupController

---

classes/Http/Action/Admin/Talk/IndexAction.php
classes/Http/Controller/Admin/TalksController.php
resources/config/routing.yml
tests/Integration/Http/Action/Admin/Talk/IndexActionTest.php
tests/Integration/Http/Controller/Admin/TalksControllerTest.php
tests/Unit/ProjectCodeTest.php

Enhancement: Extract IndexAction from TalksController

---

classes/Http/Action/Admin/Talk/ViewAction.php
classes/Http/Controller/Admin/TalksController.php
resources/config/routing.yml
tests/Integration/Http/Action/Admin/Talk/ViewActionTest.php
tests/Integration/Http/Controller/Admin/TalksControllerTest.php
tests/Unit/Http/Action/Admin/Talk/ViewActionTest.php

Enhancement: Extract ViewAction from TalksController

---

resources/views/security/login.twig

Enhancement: Improve accessibility of login form

---

classes/Http/Action/Reviewer/Speaker/ViewAction.php
classes/Http/Controller/Reviewer/SpeakersController.php
resources/config/routing.yml
resources/config/services/services.yml
tests/Integration/Http/Action/Reviewer/Speaker/ViewActionTest.php
tests/Integration/Http/Controller/Reviewer/SpeakersControllerTest.php
tests/Unit/ProjectCodeTest.php

Enhancement: Extract ViewAction from SpeakersController

---

classes/Http/Action/Forgot/IndexAction.php
resources/config/services/services.yml

Fix: Rename argument

---

classes/Http/Action/Forgot/UpdatePasswordAction.php
classes/Http/Controller/ForgotController.php
resources/config/routing.yml
resources/config/services/services.yml
tests/Integration/Http/Action/Forgot/UpdatePasswordActionTest.php
tests/Unit/Http/Action/Forgot/UpdatePasswordActionTest.php

Enhancement: Extract UpdatePasswordAction from ForgotController

---

classes/Http/Action/Talk/CreateProcessAction.php
resources/config/routing.yml
resources/config/services/services.yml
tests/Integration/Http/Action/Talk/CreateProcessActionTest.php
tests/Unit/Http/Action/Talk/CreateProcessActionTest.php

Enhancement: Turn TalkController into CreateProcessAction

---

classes/Http/Action/Security/LogOutAction.php
classes/Http/Controller/SecurityController.php
resources/config/routing.yml
tests/Integration/Http/Action/Security/LogOutActionTest.php
tests/Unit/Http/Action/Security/LogOutActionTest.php

Enhancement: Extract LogOutAction from SecurityController

---

composer.json
composer.lock
phpunit.xml.dist

Enhancement: added "pretty print" helper

---

resources/config/config_testing.yml
tests/Helper/MockAuthentication.php
tests/Helper/MockIdentityProvider.php
tests/Integration/Http/Action/DashboardActionTest.php
tests/Integration/WebTestCase.php

Fix: Rename classes

---

classes/Http/Controller/Admin/SpeakersController.php

Fix: Remove unused field

---

classes/Http/Action/Forgot/ResetProcessAction.php
classes/Http/Controller/ForgotController.php
resources/config/routing.yml
tests/Integration/Http/Action/Forgot/ResetProcessActionTest.php
tests/Unit/Http/Action/Forgot/ResetProcessActionTest.php

Enhancement: Extract ResetProcessAction from ForgotController

---

composer.json
composer.lock

This PR upgrades Twig to the 2.x branch. Hello future! 😎

Upgraded Twig to version 2

---

classes/Http/Action/Profile/ChangePasswordProcessAction.php
classes/Http/Controller/ProfileController.php
resources/config/routing.yml
tests/Integration/Http/Action/Profile/ChangePasswordProcessActionTest.php
tests/Unit/ProjectCodeTest.php

Enhancement: Extract ChangePasswordProcessAction from ProfileController

---

classes/Infrastructure/Templating/TwigExtension.php
classes/Path.php
classes/PathInterface.php
resources/views/admin/index.twig
resources/views/admin/speaker/index.twig
resources/views/admin/speaker/view.twig
resources/views/admin/talks/index.twig
resources/views/admin/talks/view.twig
resources/views/layouts/default.twig
resources/views/layouts/splash.twig
resources/views/reviewer/index.twig
resources/views/reviewer/speaker/index.twig
resources/views/reviewer/talks/index.twig
resources/views/reviewer/talks/view.twig
resources/views/security/forgot_password.twig
resources/views/security/login.twig
resources/views/security/signup.twig
tests/Unit/PathTest.php

Fix: use assets path

---

classes/Http/Controller/ProfileController.php
classes/Infrastructure/Templating/TwigExtension.php
classes/PathInterface.php
classes/WebPath.php
resources/config/services/services.yml
tests/Integration/Infrastructure/Templating/TwigExtensionTest.php
tests/Unit/WebPathTest.php

Clean and split up Path class

---

.travis.yml

Fix: Only report coverage after success

---

composer.lock

This PR updated all Symfony packages to version 3.4.3.
Reference: http://symfony.com/blog/symfony-3-4-3-released

Updated Symfony components to 3.4.3.

---

tests/Integration/WebTestCase.php

Remove hasPermission mock

---

classes/Domain/Model/Airport.php
classes/Domain/Services/AirportInformationDatabase.php

Update Airport docblock

---

classes/Http/Action/Profile/EditAction.php
classes/Http/Controller/ProfileController.php
resources/config/routing.yml
tests/Integration/Http/Action/Profile/EditActionTest.php
tests/Integration/Http/Controller/ProfileControllerTest.php
tests/Unit/Http/Action/Profile/EditActionTest.php

Enhancement: Extract EditAction from ProfileController

---

classes/Http/Action/Profile/ProcessAction.php
resources/config/routing.yml
tests/Integration/Http/Action/Profile/ProcessActionTest.php
tests/Unit/Http/Action/Profile/ProcessActionTest.php
tests/Unit/ProjectCodeTest.php

Enhancement: Turn ProfileController into ProcessAction

---

classes/Http/Action/Forgot/UpdatePasswordAction.php
classes/Http/Controller/ForgotController.php

Fixes problem with reset email code not working correctly

---

Makefile
composer.json
composer.lock

This PR
💁‍♂️ I think that as a start it could be useful to run 
```
$ make stan
```
locally.

Enhancement: Require phpstan/phpstan

---

classes/Domain/Model/Talk.php
classes/Domain/Model/User.php
classes/Infrastructure/Auth/UserInterface.php

This PR
* fixes couple of phpstan issues

fixed some phpstan issues

---

composer.lock

This PR updates all used Illuminate packages and their dependencies.
* illuminate/* (v5.5.17 => v5.5.39)
* wouterj/eloquent-bundle (1.0.1 => 1.0.2)
* nesbot/carbon (1.22.1 => 1.24.2)

Upgraded all Illuminate packages to 5.5.39

---

classes/Domain/Model/Talk.php
classes/Domain/Talk/TalkFilter.php
classes/Http/Action/Admin/Talk/IndexAction.php
classes/Http/Action/Reviewer/Talk/IndexAction.php
resources/views/admin/talks/index.twig
resources/views/reviewer/talks/index.twig

Better admin filters 2

---

README.md

Fix Table of Contents for "Grab Latest Release" headline in README.md

---

README.md

Add "/cache/env" and "/log" into writable folders

---

resources/views/security/signup.twig

Enhancement: Improve sign-up form

---

README.md

fix anchor link to docker section

---

Makefile

Enhancement: Run composer validate and composer normalize in vendor target

---

src/Domain/Speaker/SpeakerProfile.php

Fixes duplicate : in Twitter profile link that was causing Twitter profile links to not work.
Have a couple more PRs incoming for other minor quality of life fixes.

Fix Twitter link

---

resources/views/admin/index.twig
resources/views/reviewer/index.twig
src/Http/Action/Admin/DashboardAction.php
src/Http/Action/Reviewer/DashboardAction.php

Only count speakers with at least one talk on dashboard speaker count

---

src/Http/Action/Security/LogInAction.php
tests/Unit/Http/Action/Security/LogInActionTest.php

Redirect admins and reviewers to their respective dashboards on-login

---

README.md

This clarifies what to do after building the docker image.

Clarify post Docker steps

---

package.json

This PR should fix the issue with TailwindCss compilation.
Related to # https://twitter.com/grmpyprogrammer/status/1195816871171416067
Fixes # https://gist.github.com/chartjes/6f92f91f1f1c35ab677f635a8d18e1ee

fix tailwind compiling issue
